import type { Institution } from "./build";
import type { Field } from "./fields";

const STEM: Field[] = ["cs", "engineering", "data_ai", "science"];
const BROAD: Field[] = [
  "cs",
  "engineering",
  "data_ai",
  "business",
  "finance",
  "science",
  "life_health",
  "social",
  "education",
];
const FULL: Field[] = [...BROAD, "arts_design", "law"];

export const US_INSTITUTIONS: Institution[] = [
  { name: "MIT", country: "US", city: "Cambridge", tier: 1, website: "https://www.mit.edu/", fields: STEM },
  { name: "Stanford", country: "US", city: "Stanford", tier: 1, website: "https://www.stanford.edu/", fields: FULL },
  { name: "CMU", country: "US", city: "Pittsburgh", tier: 1, website: "https://www.cmu.edu/", fields: ["cs", "engineering", "data_ai", "arts_design", "business"] },
  { name: "UC Berkeley", country: "US", city: "Berkeley", tier: 1, website: "https://www.berkeley.edu/", fields: FULL },
  { name: "Caltech", country: "US", city: "Pasadena", tier: 1, website: "https://www.caltech.edu/", fields: STEM },
  { name: "Harvard", country: "US", city: "Cambridge", tier: 1, website: "https://www.harvard.edu/", fields: ["data_ai", "business", "finance", "life_health", "social", "education", "law"] },
  { name: "Princeton", country: "US", city: "Princeton", tier: 1, website: "https://www.princeton.edu/", fields: ["cs", "engineering", "science", "social"] },
  { name: "Yale", country: "US", city: "New Haven", tier: 1, website: "https://www.yale.edu/", fields: ["cs", "data_ai", "social", "arts_design", "law", "education"] },
  { name: "Columbia", country: "US", city: "New York", tier: 2, website: "https://www.columbia.edu/", fields: FULL },
  { name: "UPenn", country: "US", city: "Philadelphia", tier: 2, website: "https://www.upenn.edu/", fields: FULL },
  { name: "Cornell", country: "US", city: "Ithaca", tier: 2, website: "https://www.cornell.edu/", fields: BROAD },
  { name: "University of Chicago", country: "US", city: "Chicago", tier: 2, website: "https://www.uchicago.edu/", fields: ["cs", "data_ai", "business", "finance", "science", "social"] },
  { name: "Duke", country: "US", city: "Durham", tier: 2, website: "https://www.duke.edu/", fields: BROAD },
  { name: "Northwestern", country: "US", city: "Evanston", tier: 2, website: "https://www.northwestern.edu/", fields: BROAD },
  { name: "Johns Hopkins", country: "US", city: "Baltimore", tier: 2, website: "https://www.jhu.edu/", fields: ["cs", "engineering", "data_ai", "life_health", "science"] },
  { name: "Brown", country: "US", city: "Providence", tier: 2, website: "https://www.brown.edu/", fields: ["cs", "data_ai", "social", "arts_design"] },
  { name: "Rice", country: "US", city: "Houston", tier: 2, website: "https://www.rice.edu/", fields: STEM },
  { name: "Vanderbilt", country: "US", city: "Nashville", tier: 2, website: "https://www.vanderbilt.edu/", fields: ["cs", "engineering", "education", "social"] },
  { name: "Washington University in St. Louis", country: "US", city: "St. Louis", tier: 2, website: "https://wustl.edu/", fields: ["cs", "engineering", "business", "life_health"] },
  { name: "UCLA", country: "US", city: "Los Angeles", tier: 2, website: "https://www.ucla.edu/", fields: FULL },
  { name: "UC San Diego", country: "US", city: "San Diego", tier: 2, website: "https://ucsd.edu/", fields: ["cs", "engineering", "data_ai", "science", "life_health"] },
  { name: "USC", country: "US", city: "Los Angeles", tier: 3, website: "https://www.usc.edu/", fields: FULL },
  { name: "NYU", country: "US", city: "New York", tier: 3, website: "https://www.nyu.edu/", fields: FULL },
  { name: "University of Michigan", country: "US", city: "Ann Arbor", tier: 2, website: "https://umich.edu/", fields: FULL },
  { name: "Georgia Tech", country: "US", city: "Atlanta", tier: 3, website: "https://www.gatech.edu/", fields: ["cs", "engineering", "data_ai", "science", "business"] },
  { name: "UIUC", country: "US", city: "Urbana", tier: 2, website: "https://illinois.edu/", fields: ["cs", "engineering", "data_ai", "science", "business", "education"] },
  { name: "University of Texas at Austin", country: "US", city: "Austin", tier: 2, website: "https://www.utexas.edu/", fields: BROAD },
  { name: "University of Washington", country: "US", city: "Seattle", tier: 2, website: "https://www.washington.edu/", fields: BROAD },
  { name: "Purdue", country: "US", city: "West Lafayette", tier: 3, website: "https://www.purdue.edu/", fields: ["cs", "engineering", "data_ai", "science", "education"] },
  { name: "Boston University", country: "US", city: "Boston", tier: 3, website: "https://www.bu.edu/", fields: BROAD },
  { name: "University of Wisconsin-Madison", country: "US", city: "Madison", tier: 3, website: "https://www.wisc.edu/", fields: BROAD },
  { name: "Ohio State University", country: "US", city: "Columbus", tier: 3, website: "https://www.osu.edu/", fields: BROAD },
  { name: "Penn State", country: "US", city: "University Park", tier: 3, website: "https://www.psu.edu/", fields: BROAD },
  { name: "University of Florida", country: "US", city: "Gainesville", tier: 3, website: "https://www.ufl.edu/", fields: BROAD },
  { name: "University of Maryland", country: "US", city: "College Park", tier: 3, website: "https://www.umd.edu/", fields: ["cs", "engineering", "data_ai", "science", "social", "education"] },
  { name: "UC Irvine", country: "US", city: "Irvine", tier: 3, website: "https://uci.edu/", fields: ["cs", "engineering", "data_ai", "science", "business", "arts_design"] },
  { name: "UC Davis", country: "US", city: "Davis", tier: 3, website: "https://www.ucdavis.edu/", fields: ["cs", "engineering", "science", "life_health", "education"] },
  { name: "Northeastern", country: "US", city: "Boston", tier: 3, website: "https://www.northeastern.edu/", fields: ["cs", "engineering", "data_ai", "business", "life_health"] },
  { name: "Arizona State University", country: "US", city: "Tempe", tier: 3, website: "https://www.asu.edu/", fields: BROAD },
  { name: "University of Minnesota", country: "US", city: "Minneapolis", tier: 3, website: "https://twin-cities.umn.edu/", fields: BROAD },
];
