/** Used when DB is unavailable so UI still runs with mock evaluate */
export const MOCK_SCHOOLS = [
  {
    id: "mock-cmu",
    slug: "cmu-computer-science-ms-us",
    name: "CMU",
    program: "Computer Science",
    degree: "MS",
    country: "US",
    field: "cs",
    city: "Pittsburgh",
    avgGpa: 3.85,
    minGpa: 3.3,
    minToefl: 100,
    minIelts: 7.0,
    gpaScale: 4.0,
    website: "https://www.cs.cmu.edu/",
    admissionRequirements: "Strong CS foundation; GRE optional for some tracks.",
    tier: 1,
  },
  {
    id: "mock-lse",
    slug: "lse-finance-msc-uk",
    name: "LSE",
    program: "Finance",
    degree: "MSc",
    country: "UK",
    field: "finance",
    city: "London",
    avgGpa: 3.7,
    minGpa: 3.3,
    minToefl: null,
    minIelts: 7.0,
    gpaScale: 4.0,
    website: "https://www.lse.ac.uk/",
    admissionRequirements: "Competitive MSc Finance; IELTS 7.0 typical.",
    tier: 1,
  },
  {
    id: "mock-melbourne",
    slug: "university-of-melbourne-design-ma-au",
    name: "University of Melbourne",
    program: "Design",
    degree: "MA",
    country: "AU",
    field: "arts_design",
    city: "Melbourne",
    avgGpa: 3.45,
    minGpa: 3.0,
    minToefl: null,
    minIelts: 6.5,
    gpaScale: 4.0,
    website: "https://www.unimelb.edu.au/",
    admissionRequirements: "Portfolio-focused design masters; IELTS 6.5+.",
    tier: 1,
  },
];
