"""Cambridge IELTS 12 Tests 1–4 listening data for mock pages."""

from __future__ import annotations


def ans(*v):
    return list(v)


def explain(*v):
    return "答案：" + " / ".join(v) + "。"


def _q(no, *answers, q=None, options=None):
    item = {"id": f"L{no}", "no": no, "answer": ans(*answers), "explain": explain(*answers)}
    if q is not None:
        item["q"] = q
    if options is not None:
        item["options"] = options
    return item


def _multi_pair(a, b, letters):
    text = "选两项（顺序不限）：" + " 与 ".join(letters) + "。"
    return [
        {"id": f"L{a}", "no": a, "explain": text},
        {"id": f"L{b}", "no": b, "explain": text},
    ]


def listening_tests():
    return {1: _T1, 2: _T2, 3: _T3, 4: _T4}


def _test(n, sections):
    return {"meta": {"volume": 12, "testNo": n}, "durationMin": 32, "sections": sections}


def _sec(n, test_no, groups):
    return {"id": n, "audio": f"ielts12_test{test_no}_audio{n}.mp3", "groups": groups}


_T1 = _test(1, [
    _sec(1, 1, [
        {
            "kind": "note",
            "title": "Questions 1–10",
            "instruction": "Complete the notes below.<br>Write ONE WORD AND/OR A NUMBER for each answer.",
            "noteTitle": "FAMILY EXCURSIONS",
            "lines": [
                {"h": "Cruise on a lake"},
                {"plain": True, "html": "Example: Travel on an old steamship"},
                {"bullet": True, "html": "Can take photos of the <Q n=\"1\"> that surround the lake"},
                {"h": "Farm visit"},
                {"bullet": True, "html": "Children can help feed the sheep"},
                {"bullet": True, "html": "Visit can include a 40-minute ride on a <Q n=\"2\">"},
                {"bullet": True, "html": "Visitors can walk in the farm’s <Q n=\"3\"> by the lake"},
                {"bullet": True, "html": "<Q n=\"4\"> is available at extra cost"},
                {"h": "Cycling trips"},
                {"bullet": True, "html": "Cyclists explore the Back Road"},
                {"bullet": True, "html": "A <Q n=\"5\"> is provided"},
                {"bullet": True, "html": "Only suitable for cyclists who have some <Q n=\"6\">"},
                {"bullet": True, "html": "Bikes can be hired from <Q n=\"7\"> (near the Cruise Ship Terminal)"},
                {"bullet": True, "html": "Cyclists need:"},
                {"bullet": True, "sub": True, "html": "a repair kit"},
                {"bullet": True, "sub": True, "html": "food and drink"},
                {"bullet": True, "sub": True, "html": "a <Q n=\"8\"> (can be hired)"},
                {"bullet": True, "html": "There are no <Q n=\"9\"> or accommodation in the area"},
                {"h": "Cost"},
                {"bullet": True, "html": "Total cost for whole family of cruise and farm visit: £<Q n=\"10\">"},
            ],
            "questions": [
                _q(1, "mountains"),
                _q(2, "horse"),
                _q(3, "garden", "gardens"),
                _q(4, "lunch"),
                _q(5, "map"),
                _q(6, "experience"),
                _q(7, "Ratchesons", "Ratcheson"),
                _q(8, "helmet"),
                _q(9, "shops"),
                _q(10, "267"),
            ],
        },
    ]),
    _sec(2, 1, [
        {
            "kind": "mcq",
            "title": "Questions 11–14",
            "instruction": "Choose the correct letter, A, B or C.",
            "heading": "",
            "questions": [
                _q(11, "A", q="According to the manager, what do most people like about the job of kitchen assistant?",
                   options={"A": "the variety of work", "B": "the friendly atmosphere", "C": "the opportunities for promotion"}),
                _q(12, "A", q="The manager is concerned about some of the new staff’s",
                   options={"A": "jewellery.", "B": "hair styles.", "C": "shoes."}),
                _q(13, "C", q="The manager says that the day is likely to be busy for kitchen staff because",
                   options={"A": "it is a public holiday.", "B": "the head chef is absent.", "C": "the restaurant is almost fully booked."}),
                _q(14, "C", q="Only kitchen staff who are 18 or older are allowed to use",
                   options={"A": "the waste disposal unit.", "B": "the electric mixer.", "C": "the meat slicer."}),
            ],
        },
        {
            "kind": "multi",
            "title": "Questions 15 and 16",
            "instruction": "Choose TWO letters, A–E.<br>According to the manager, which TWO things can make the job of kitchen assistant stressful?",
            "box": {
                "A": "They have to follow orders immediately.",
                "B": "The kitchen gets very hot.",
                "C": "They may not be able to take a break.",
                "D": "They have to do overtime.",
                "E": "The work is physically demanding.",
            },
            "groupId": "L15_16",
            "answerSet": ["A", "E"],
            "questions": _multi_pair(15, 16, ["A", "E"]),
        },
        {
            "kind": "match",
            "title": "Questions 17–20",
            "instruction": "What is the responsibility of each of the following restaurant staff?<br>Choose FOUR answers from the box and write the correct letter, A–F, next to Questions 17–20.",
            "boxTitle": "Responsibilities",
            "box": {
                "A": "training courses",
                "B": "food stocks",
                "C": "first aid",
                "D": "breakages",
                "E": "staff discounts",
                "F": "timetables",
            },
            "subTitle": "Restaurant staff",
            "questions": [
                _q(17, "F", q="Joy Parkins"),
                _q(18, "C", q="David Field"),
                _q(19, "D", q="Dexter Wills"),
                _q(20, "B", q="Mike Smith"),
            ],
        },
    ]),
    _sec(3, 1, [
        {
            "kind": "mcq",
            "title": "Questions 21–23",
            "instruction": "Choose the correct letter, A, B or C.",
            "heading": "Paper on Public Libraries",
            "questions": [
                _q(21, "B", q="What will be the main topic of Trudie and Stewart’s paper?",
                   options={"A": "how public library services are organised in different countries",
                            "B": "how changes in society are reflected in public libraries",
                            "C": "how the funding of public libraries has changed"}),
                _q(22, "C", q="They agree that one disadvantage of free digitalised books is that",
                   options={"A": "they may take a long time to read.",
                            "B": "they can be difficult to read.",
                            "C": "they are generally old."}),
                _q(23, "C", q="Stewart expects that in the future libraries will",
                   options={"A": "maintain their traditional function.",
                            "B": "become centres for local communities.",
                            "C": "no longer contain any books."}),
            ],
        },
        {
            "kind": "note",
            "title": "Questions 24–30",
            "instruction": "Complete the notes below.<br>Write ONE WORD ONLY for each answer.",
            "noteTitle": "Study of local library: possible questions",
            "lines": [
                {"bullet": True, "html": "whether it has a <Q n=\"24\"> of its own"},
                {"bullet": True, "html": "its policy regarding noise of various kinds"},
                {"bullet": True, "html": "how it’s affected by laws regarding all aspects of <Q n=\"25\">"},
                {"bullet": True, "html": "how the design needs to take the <Q n=\"26\"> of customers into account"},
                {"bullet": True, "html": "what <Q n=\"27\"> is required in case of accidents"},
                {"bullet": True, "html": "why a famous person’s <Q n=\"28\"> is located in the library"},
                {"bullet": True, "html": "whether it has a <Q n=\"29\"> of local organisations"},
                {"bullet": True, "html": "how it’s different from a library in a <Q n=\"30\">"},
            ],
            "questions": [
                _q(24, "budget"),
                _q(25, "employment"),
                _q(26, "safety"),
                _q(27, "insurance"),
                _q(28, "diary"),
                _q(29, "database"),
                _q(30, "museum"),
            ],
        },
    ]),
    _sec(4, 1, [
        {
            "kind": "note",
            "title": "Questions 31–40",
            "instruction": "Complete the notes below.<br>Write NO MORE THAN TWO WORDS for each answer.",
            "noteTitle": "Four business values",
            "lines": [
                {"plain": True, "html": "Many business values can result in <Q n=\"31\">"},
                {"plain": True, "html": "Senior managers need to understand and deal with the potential <Q n=\"32\"> that may result."},
                {"h": "Collaboration"},
                {"bullet": True, "html": "During a training course, the speaker was in a team that had to build a <Q n=\"33\">"},
                {"bullet": True, "html": "Other teams experienced <Q n=\"34\"> from trying to collaborate."},
                {"bullet": True, "html": "The speaker’s team won because they reduced collaboration."},
                {"bullet": True, "html": "Sales of a <Q n=\"35\"> were poor because of collaboration."},
                {"h": "Industriousness"},
                {"bullet": True, "html": "Hard work may be a bad use of various company <Q n=\"36\">"},
                {"bullet": True, "html": "The word ‘lazy’ in this context refers to people who avoid doing tasks that are <Q n=\"37\">"},
                {"h": "Creativity"},
                {"bullet": True, "html": "An advertising campaign for a <Q n=\"38\"> was memorable but failed to boost sales."},
                {"bullet": True, "html": "Creativity should be used as a response to a particular <Q n=\"39\">"},
                {"h": "Excellence"},
                {"bullet": True, "html": "According to one study, on average, pioneers had a <Q n=\"40\"> that was far higher than that of followers."},
                {"bullet": True, "html": "Companies that always aim at excellence may miss opportunities."},
            ],
            "questions": [
                _q(31, "damage"),
                _q(32, "side effects"),
                _q(33, "bridge"),
                _q(34, "confusion"),
                _q(35, "smartphone"),
                _q(36, "resources"),
                _q(37, "unnecessary", "not necessary"),
                _q(38, "chocolate bar"),
                _q(39, "problem"),
                _q(40, "market share"),
            ],
        },
    ]),
])


_T2 = _test(2, [
    _sec(1, 2, [
        {
            "kind": "note",
            "title": "Questions 1–10",
            "instruction": "Complete the notes below.<br>Write ONE WORD AND/OR A NUMBER for each answer.",
            "noteTitle": "Events during Kenton Festival",
            "lines": [
                {"plain": True, "html": "Example: Start date: 16th May"},
                {"h": "Opening ceremony (first day)"},
                {"bullet": True, "html": "In town centre, starting at <Q n=\"1\">"},
                {"bullet": True, "html": "The mayor will make a speech"},
                {"bullet": True, "html": "A <Q n=\"2\"> will perform"},
                {"bullet": True, "html": "Performance of a <Q n=\"3\"> about Helen Tungate (a <Q n=\"4\">)"},
                {"bullet": True, "html": "Evening fireworks display situated across the <Q n=\"5\">"},
                {"h": "Other events"},
                {"bullet": True, "html": "Videos about relationships that children have with their <Q n=\"6\">"},
                {"bullet": True, "html": "Venue: <Q n=\"7\"> House"},
                {"bullet": True, "html": "Performance of <Q n=\"8\"> dances"},
                {"bullet": True, "html": "Venue: the <Q n=\"9\"> market in the town centre"},
                {"bullet": True, "html": "Time: 2 and 5 pm every day except 1st day of festival"},
                {"bullet": True, "html": "Several professional concerts and one by children"},
                {"bullet": True, "html": "Venue: library"},
                {"bullet": True, "html": "Time: 6.30 pm on the 18th"},
                {"bullet": True, "html": "Tickets available online from festival box office and from shops which have the festival <Q n=\"10\"> in their windows"},
            ],
            "questions": [
                _q(1, "2.45", "2:45", "2.45pm", "2.45 pm"),
                _q(2, "band"),
                _q(3, "play"),
                _q(4, "scientist"),
                _q(5, "river"),
                _q(6, "grandparents"),
                _q(7, "Handsworth"),
                _q(8, "traditional"),
                _q(9, "outdoor"),
                _q(10, "logo"),
            ],
        },
    ]),
    _sec(2, 2, [
        {
            "kind": "mcq",
            "title": "Questions 11–15",
            "instruction": "Choose the correct letter, A, B or C.",
            "heading": "",
            "questions": [
                _q(11, "B", q="When the group meet at the airport they will have",
                   options={"A": "breakfast.", "B": "coffee.", "C": "lunch."}),
                _q(12, "C", q="The group will be met at Munich Airport by",
                   options={"A": "an employee at the National Theatre.",
                            "B": "a theatre manager.",
                            "C": "a tour operator."}),
                _q(13, "A", q="How much will they pay per night for a double room at the hotel?",
                   options={"A": "110 euros", "B": "120 euros", "C": "150 euros"}),
                _q(14, "B", q="What type of restaurant will they go to on Tuesday evening?",
                   options={"A": "an Italian restaurant",
                            "B": "a Lebanese restaurant",
                            "C": "a typical restaurant of the region"}),
                _q(15, "C", q="Who will they meet on Wednesday afternoon?",
                   options={"A": "an actor", "B": "a playwright", "C": "a theatre director"}),
            ],
        },
        {
            "kind": "match",
            "title": "Questions 16–20",
            "instruction": "What does the man say about the play on each of the following days?<br>Choose FIVE answers from the box and write the correct letter, A–G, next to Questions 16–20.",
            "boxTitle": "Comments",
            "box": {
                "A": "The playwright will be present.",
                "B": "The play was written to celebrate an anniversary.",
                "C": "The play will be performed inside a historic building.",
                "D": "The play will be accompanied by live music.",
                "E": "The play will be performed outdoors.",
                "F": "The play will be performed for the first time.",
                "G": "The performance will be attended by officials from the town.",
            },
            "subTitle": "Days",
            "questions": [
                _q(16, "F", q="Wednesday"),
                _q(17, "B", q="Thursday"),
                _q(18, "E", q="Friday"),
                _q(19, "G", q="Saturday"),
                _q(20, "C", q="Monday"),
            ],
        },
    ]),
    _sec(3, 2, [
        {
            "kind": "mcq",
            "title": "Questions 21–25",
            "instruction": "Choose the correct letter, A, B or C.",
            "heading": "",
            "questions": [
                _q(21, "C", q="James chose to take Scandinavian Studies because when he was a child",
                   options={"A": "he was often taken to Denmark.",
                            "B": "his mother spoke to him in Danish.",
                            "C": "a number of Danish people visited his family."}),
                _q(22, "B", q="When he graduates, James would like to",
                   options={"A": "take a postgraduate course.",
                            "B": "work in the media.",
                            "C": "become a translator."}),
                _q(23, "C", q="Which course will end this term?",
                   options={"A": "Swedish cinema",
                            "B": "Danish television programmes",
                            "C": "Scandinavian literature"}),
                _q(24, "A", q="They agree that James’s literature paper this term will be on",
                   options={"A": "19th century playwrights.",
                            "B": "the Icelandic sagas.",
                            "C": "modern Scandinavian novels."}),
                _q(25, "C", q="Beth recommends that James’s paper should be",
                   options={"A": "a historical overview of the genre.",
                            "B": "an in-depth analysis of a single writer.",
                            "C": "a study of the social background to the literature."}),
            ],
        },
        {
            "kind": "match",
            "title": "Questions 26–30",
            "instruction": "Complete the flow-chart below.<br>Choose FIVE answers from the box and write the correct letter, A–G, next to Questions 26–30.",
            "boxTitle": "",
            "box": {
                "A": "the topic",
                "B": "the structure",
                "C": "the references",
                "D": "the format",
                "E": "the sources",
                "F": "the vocabulary",
                "G": "the key points",
            },
            "subTitle": "How James will write his paper on the Vikings",
            "questions": [
                _q(26, "E", q="Choose information from …"),
                _q(27, "G", q="Make notes of …"),
                _q(28, "D", q="Decide on …"),
                _q(29, "C", q="Find some … to use"),
                _q(30, "A", q="Check …"),
            ],
        },
    ]),
    _sec(4, 2, [
        {
            "kind": "note",
            "title": "Questions 31–40",
            "instruction": "Complete the notes below.<br>Write ONE WORD ONLY for each answer.",
            "noteTitle": "Conflict at work",
            "lines": [
                {"plain": True, "html": "Conflict mostly consists of behaviour in the general category of <Q n=\"31\">"},
                {"plain": True, "html": "Often a result of people wanting to prove their <Q n=\"32\">"},
                {"plain": True, "html": "Also caused by differences in <Q n=\"33\"> between people"},
                {"plain": True, "html": "<Q n=\"34\"> conflicts: people more concerned about own team than about company"},
                {"plain": True, "html": "Conflict-related stress can cause <Q n=\"35\"> that may last for months"},
                {"h": "Chief Executives (CEOs)"},
                {"bullet": True, "html": "Many have both <Q n=\"36\"> and anxiety"},
                {"bullet": True, "html": "May not like to have their decisions questioned."},
                {"bullet": True, "html": "There may be conflict between people who have different <Q n=\"37\">"},
                {"h": "Other managers"},
                {"bullet": True, "html": "A structure that is more <Q n=\"38\"> may create a feeling of uncertainty about who staff should report to."},
                {"h": "Minimising conflict"},
                {"bullet": True, "html": "Bosses need to try hard to gain <Q n=\"39\">"},
                {"bullet": True, "html": "Someone from outside the company may be given the role of <Q n=\"40\"> in order to resolve conflicts."},
            ],
            "questions": [
                _q(31, "bullying"),
                _q(32, "superiority"),
                _q(33, "personality"),
                _q(34, "structural"),
                _q(35, "absence"),
                _q(36, "confidence"),
                _q(37, "visions"),
                _q(38, "democratic"),
                _q(39, "respect"),
                _q(40, "mediator"),
            ],
        },
    ]),
])


_T3 = _test(3, [
    _sec(1, 3, [
        {
            "kind": "note",
            "title": "Questions 1–10",
            "instruction": "Complete the notes below.<br>Write ONE WORD ONLY for each answer.",
            "noteTitle": "PUBLIC LIBRARY",
            "lines": [
                {"plain": True, "html": "Example: The library re-opened last month"},
                {"h": "The library now has:"},
                {"bullet": True, "html": "a seating area with magazines"},
                {"bullet": True, "html": "an expanded section for books on <Q n=\"1\">"},
                {"bullet": True, "html": "a new section on local <Q n=\"2\">"},
                {"bullet": True, "html": "a community room for meetings (also possible to <Q n=\"3\"> there)"},
                {"bullet": True, "html": "a new section of books for <Q n=\"4\">"},
                {"h": "For younger children:"},
                {"bullet": True, "html": "the next Science Club meeting: experiments using things from your <Q n=\"5\">"},
                {"bullet": True, "html": "Reading Challenge: read six books during the holidays"},
                {"h": "For adults:"},
                {"bullet": True, "html": "this Friday: a local author talks about a novel based on a real <Q n=\"6\">"},
                {"bullet": True, "html": "IT support is available on Tuesdays – no <Q n=\"7\"> is necessary"},
                {"bullet": True, "html": "free check of blood <Q n=\"8\"> and cholesterol levels (over 60s only)"},
                {"h": "Other information:"},
                {"bullet": True, "html": "the library shop sells wall-charts, cards and <Q n=\"9\">"},
                {"bullet": True, "html": "evenings and weekends: free <Q n=\"10\"> is available"},
            ],
            "questions": [
                _q(1, "travel", "travelling", "traveling"),
                _q(2, "history"),
                _q(3, "study"),
                _q(4, "teenagers"),
                _q(5, "kitchen"),
                _q(6, "crime"),
                _q(7, "appointment", "booking"),
                _q(8, "sugar"),
                _q(9, "stamps"),
                _q(10, "parking"),
            ],
        },
    ]),
    _sec(2, 3, [
        {
            "kind": "multi",
            "title": "Questions 11 and 12",
            "instruction": "Choose TWO letters, A–E.<br>Which TWO age groups are taking increasing numbers of holidays with BC Travel?",
            "box": {
                "A": "16-30 years",
                "B": "31-42 years",
                "C": "43-54 years",
                "D": "55-64 years",
                "E": "over 65 years",
            },
            "groupId": "L11_12",
            "answerSet": ["D", "E"],
            "questions": _multi_pair(11, 12, ["D", "E"]),
        },
        {
            "kind": "multi",
            "title": "Questions 13 and 14",
            "instruction": "Choose TWO letters, A–E.<br>Which TWO are the main reasons given for the popularity of activity holidays?",
            "box": {
                "A": "Clients make new friends.",
                "B": "Clients learn a useful skill.",
                "C": "Clients learn about a different culture.",
                "D": "Clients are excited by the risk involved.",
                "E": "Clients find them good value for money.",
            },
            "groupId": "L13_14",
            "answerSet": ["A", "C"],
            "questions": _multi_pair(13, 14, ["A", "C"]),
        },
        {
            "kind": "mcq",
            "title": "Questions 15–17",
            "instruction": "Choose the correct letter, A, B or C.",
            "heading": "",
            "questions": [
                _q(15, "C", q="How does BC Travel plan to expand the painting holidays?",
                   options={"A": "by adding to the number of locations",
                            "B": "by increasing the range of levels",
                            "C": "by employing more teachers"}),
                _q(16, "B", q="Why are BC Travel’s cooking holidays unusual?",
                   options={"A": "They only use organic foods.",
                            "B": "They have an international focus.",
                            "C": "They mainly involve vegetarian dishes."}),
                _q(17, "A", q="What does the speaker say about the photography holidays?",
                   options={"A": "Clients receive individual tuition.",
                            "B": "The tutors are also trained guides.",
                            "C": "Advice is given on selling photographs."}),
            ],
        },
        {
            "kind": "table",
            "title": "Questions 18–20",
            "instruction": "Complete the table below.<br>Write ONE WORD ONLY for each answer.",
            "tableTitle": "Fitness Holidays",
            "cols": ["Location", "Main focus", "Other comments"],
            "rows": [
                ["Ireland and Italy", "general fitness", "personally designed programme; also reduces <Q n=\"18\">"],
                ["Greece", "<Q n=\"19\"> control", "includes exercise on the beach"],
                ["Morocco", "mountain biking", "wide variety of levels; one holiday that is specially designed for <Q n=\"20\">"],
            ],
            "questions": [
                _q(18, "stress"),
                _q(19, "weight"),
                _q(20, "families"),
            ],
        },
    ]),
    _sec(3, 3, [
        {
            "kind": "match",
            "title": "Questions 21–26",
            "instruction": "Complete the flow-chart below.<br>Choose SIX answers from the box and write the correct letter, A–H, next to Questions 21–26.",
            "boxTitle": "",
            "box": {
                "A": "patterns",
                "B": "names",
                "C": "sources",
                "D": "questions",
                "E": "employees",
                "F": "solutions",
                "G": "headings",
                "H": "officials",
            },
            "subTitle": "STAGES IN DOING A TOURISM CASE STUDY",
            "questions": [
                _q(21, "C", q="Locate and read relevant articles, noting key information and also …"),
                _q(22, "E", q="Select interviewees – these may be site …"),
                _q(23, "H", q="visitors or city …"),
                _q(24, "B", q="Check whether … of interviewees can be used"),
                _q(25, "A", q="Select relevant information and try to identify …"),
                _q(26, "F", q="Do NOT end with …"),
            ],
        },
        {
            "kind": "mcq",
            "title": "Questions 27–30",
            "instruction": "Choose the correct letter, A, B or C.",
            "heading": "",
            "questions": [
                _q(27, "A", q="Natalie and Dave agree one reason why so few people visit Horton Castle is that",
                   options={"A": "the publicity is poor.",
                            "B": "it is difficult to get to.",
                            "C": "there is little there of interest."}),
                _q(28, "C", q="Natalie and Dave agree that the greatest problem with a visitor centre could be",
                   options={"A": "covering the investment costs.",
                            "B": "finding a big enough space for it.",
                            "C": "dealing with planning restrictions."}),
                _q(29, "B", q="What does Dave say about conditions in the town of Horton?",
                   options={"A": "There is a lot of unemployment.",
                            "B": "There are few people of working age.",
                            "C": "There are opportunities for skilled workers."}),
                _q(30, "B", q="According to Natalie, one way to prevent damage to the castle site would be to",
                   options={"A": "insist visitors have a guide.",
                            "B": "make visitors keep to the paths.",
                            "C": "limit visitor numbers."}),
            ],
        },
    ]),
    _sec(4, 3, [
        {
            "kind": "note",
            "title": "Questions 31–40",
            "instruction": "Complete the notes below.<br>Write ONE WORD ONLY for each answer.",
            "noteTitle": "The effects of environmental change on birds",
            "lines": [
                {"h": "Mercury (Hg)"},
                {"bullet": True, "html": "Highly toxic"},
                {"bullet": True, "html": "Released into the atmosphere from coal"},
                {"bullet": True, "html": "In water it may be consumed by fish"},
                {"bullet": True, "html": "It has also recently been found to affect birds which feed on <Q n=\"31\">"},
                {"h": "Research on effects of mercury on birds"},
                {"plain": True, "html": "Claire Varian-Ramos is investigating:"},
                {"bullet": True, "html": "the effects on birds’ <Q n=\"32\"> or mental processes, e.g. memory"},
                {"bullet": True, "html": "the effects on bird song (usually learned from a bird’s <Q n=\"33\">)"},
                {"h": "Findings:"},
                {"bullet": True, "html": "songs learned by birds exposed to mercury are less <Q n=\"34\">"},
                {"bullet": True, "html": "this may have a negative effect on birds’ <Q n=\"35\">"},
                {"h": "Lab-based studies:"},
                {"bullet": True, "html": "allow more <Q n=\"36\"> for the experimenter"},
                {"h": "Implications for humans"},
                {"bullet": True, "html": "Migrating birds such as <Q n=\"37\"> containing mercury may be eaten by humans"},
                {"bullet": True, "html": "Mercury also causes problems in learning <Q n=\"38\">"},
                {"bullet": True, "html": "Mercury in a mother’s body from <Q n=\"39\"> may affect the unborn child"},
                {"bullet": True, "html": "New regulations for mercury emissions will affect everyone’s energy <Q n=\"40\">"},
            ],
            "questions": [
                _q(31, "insects"),
                _q(32, "behaviour", "behavior"),
                _q(33, "father"),
                _q(34, "complex", "complicated"),
                _q(35, "reproduction", "breeding"),
                _q(36, "control"),
                _q(37, "duck", "ducks"),
                _q(38, "language"),
                _q(39, "food"),
                _q(40, "cost", "costs", "price", "prices", "bill", "bills"),
            ],
        },
    ]),
])


_T4 = _test(4, [
    _sec(1, 4, [
        {
            "kind": "note",
            "title": "Questions 1–10",
            "instruction": "Complete the notes below.<br>Write ONE WORD AND/OR A NUMBER for each answer.",
            "noteTitle": "Cycle tour leader: Applicant enquiry",
            "lines": [
                {"plain": True, "html": "Example: Name: Margaret Smith"},
                {"h": "About the applicant:"},
                {"bullet": True, "html": "wants a <Q n=\"1\"> job"},
                {"bullet": True, "html": "will soon start work as a <Q n=\"2\">"},
                {"bullet": True, "html": "has led cycle trips in <Q n=\"3\">"},
                {"bullet": True, "html": "interested in being a leader of a cycling trip for families"},
                {"bullet": True, "html": "is currently doing voluntary work with members of a <Q n=\"4\"> club"},
                {"bullet": True, "html": "available for five months from the 1st of <Q n=\"5\">"},
                {"bullet": True, "html": "can’t eat <Q n=\"6\">"},
                {"h": "Contact details:"},
                {"bullet": True, "html": "address: 27 <Q n=\"7\"> Place, Dumfries"},
                {"bullet": True, "html": "postcode: <Q n=\"8\">"},
                {"h": "Interview:"},
                {"bullet": True, "html": "interview at 2.30 pm on <Q n=\"9\">"},
                {"bullet": True, "html": "will plan a short <Q n=\"10\"> about being a tour guide"},
            ],
            "questions": [
                _q(1, "temporary"),
                _q(2, "doctor"),
                _q(3, "Africa"),
                _q(4, "youth"),
                _q(5, "May"),
                _q(6, "cheese"),
                _q(7, "Arbuthnot"),
                _q(8, "DG7 4PH", "DG74PH"),
                _q(9, "Tuesday"),
                _q(10, "talk", "presentation"),
            ],
        },
    ]),
    _sec(2, 4, [
        {
            "kind": "mcq",
            "title": "Questions 11–14",
            "instruction": "Choose the correct letter, A, B or C.",
            "heading": "",
            "questions": [
                _q(11, "A", q="Which is the most rapidly-growing group of residents in the Sheepmarket area?",
                   options={"A": "young professional people",
                            "B": "students from the university",
                            "C": "employees in the local market"}),
                _q(12, "C", q="The speaker recommends the side streets in the Sheepmarket for their",
                   options={"A": "international restaurants.",
                            "B": "historical buildings.",
                            "C": "arts and crafts."}),
                _q(13, "B", q="Clothes designed by entrants for the Young Fashion competition must",
                   options={"A": "be modelled by the designers themselves.",
                            "B": "be inspired by aspects of contemporary culture.",
                            "C": "be made from locally produced materials."}),
                _q(14, "B", q="Car parking is free in some car parks if you",
                   options={"A": "stay for less than an hour.",
                            "B": "buy something in the shops.",
                            "C": "park in the evenings or at weekends."}),
            ],
        },
        {
            "kind": "map",
            "title": "Questions 15–20",
            "instruction": "Label the map below.<br>Write the correct letter, A–I, next to Questions 15–20.",
            "mapTitle": "Art and History in the Sheepmarket",
            "image": "ielts12_test4_map.png",
            "letters": ["A", "B", "C", "D", "E", "F", "G", "H", "I"],
            "questions": [
                _q(15, "H", q="The Reynolds House"),
                _q(16, "C", q="The Thumb"),
                _q(17, "F", q="The Museum"),
                _q(18, "G", q="The Contemporary Art Gallery"),
                _q(19, "I", q="The Warner Gallery"),
                _q(20, "B", q="Nucleus"),
            ],
        },
    ]),
    _sec(3, 4, [
        {
            "kind": "note",
            "title": "Questions 21–24",
            "instruction": "Complete the table below.<br>Write ONE WORD ONLY for each answer.",
            "noteTitle": "Presentation on film adaptations of Shakespeare’s plays",
            "lines": [
                {"h": "Stages of presentation:"},
                {"bullet": True, "html": "Introduce Giannetti’s book containing a <Q n=\"21\"> of adaptations"},
                {"bullet": True, "html": "Organise notes"},
                {"bullet": True, "html": "Ask class to suggest the <Q n=\"22\"> adaptations (no further work needed)"},
                {"bullet": True, "html": "Present Rachel Malchow’s ideas"},
                {"bullet": True, "html": "Prepare some <Q n=\"23\">"},
                {"bullet": True, "html": "Discuss relationship between adaptations and <Q n=\"24\"> at the time of making the film (no further work needed)"},
            ],
            "questions": [
                _q(21, "classification"),
                _q(22, "worst"),
                _q(23, "slides"),
                _q(24, "issues"),
            ],
        },
        {
            "kind": "match",
            "title": "Questions 25–30",
            "instruction": "What do the speakers say about each of the following films?<br>Choose SIX answers from the box and write the correct letter, A–G, next to Questions 25–30.",
            "boxTitle": "Comments",
            "box": {
                "A": "clearly shows the historical period",
                "B": "contains only parts of the play",
                "C": "is too similar to another kind of film",
                "D": "turned out to be unpopular with audiences",
                "E": "presents the play in a different period from the original",
                "F": "sets the original in a different country",
                "G": "incorporates a variety of art forms",
            },
            "subTitle": "Films",
            "questions": [
                _q(25, "F", q="Ran"),
                _q(26, "A", q="Much Ado About Nothing"),
                _q(27, "E", q="Romeo & Juliet"),
                _q(28, "C", q="Hamlet"),
                _q(29, "G", q="Prospero’s Books"),
                _q(30, "B", q="Looking for Richard"),
            ],
        },
    ]),
    _sec(4, 4, [
        {
            "kind": "note",
            "title": "Questions 31–40",
            "instruction": "Complete the notes below.<br>Write ONE WORD ONLY for each answer.",
            "noteTitle": "Noise in Cities",
            "lines": [
                {"plain": True, "html": "Past research focused on noise level (measured in decibels) and people’s responses."},
                {"h": "Noise ‘maps’"},
                {"bullet": True, "html": "show that the highest noise levels are usually found on roads"},
                {"bullet": True, "html": "do not show other sources of noise, e.g. when windows are open or people’s neighbours are in their <Q n=\"31\">"},
                {"bullet": True, "html": "ignore variations in people’s perceptions of noise"},
                {"bullet": True, "html": "have made people realize that the noise is a <Q n=\"32\"> issue that must be dealt with"},
                {"h": "Problems caused by noise"},
                {"bullet": True, "html": "sleep disturbance"},
                {"bullet": True, "html": "increase in amount of stress"},
                {"bullet": True, "html": "effect on the <Q n=\"33\"> of schoolchildren"},
                {"h": "Different types of noise"},
                {"bullet": True, "html": "Some noises can be considered pleasant e.g. the sound of a <Q n=\"34\"> in a town"},
                {"bullet": True, "html": "To investigate this, researchers may use methods from <Q n=\"35\"> sciences e.g. questionnaires"},
                {"h": "What people want"},
                {"bullet": True, "html": "Plenty of activity in urban environments which are <Q n=\"36\">, but also allow people to relax"},
                {"h": "But architects and town planners"},
                {"bullet": True, "html": "do not get much <Q n=\"37\"> in acoustics"},
                {"bullet": True, "html": "regard sound as the responsibility of engineers"},
                {"h": "Understanding sound as an art form"},
                {"plain": True, "html": "We need to know:"},
                {"bullet": True, "html": "how sound relates to <Q n=\"38\">"},
                {"bullet": True, "html": "what can be learnt from psychology about the effects of sound"},
                {"bullet": True, "html": "whether physics can help us understand the <Q n=\"39\"> of sound"},
                {"h": "Virtual reality programs"},
                {"bullet": True, "html": "advantage: predict the effect of buildings"},
                {"bullet": True, "html": "current disadvantage: they are <Q n=\"40\">"},
            ],
            "questions": [
                _q(31, "garden", "gardens"),
                _q(32, "political"),
                _q(33, "work", "study"),
                _q(34, "fountain"),
                _q(35, "social"),
                _q(36, "lively"),
                _q(37, "training"),
                _q(38, "culture"),
                _q(39, "nature"),
                _q(40, "silent"),
            ],
        },
    ]),
])


if __name__ == "__main__":
    for n, test in listening_tests().items():
        qs = [q for s in test["sections"] for g in s["groups"] for q in g["questions"]]
        nos = [q["no"] for q in qs]
        assert nos == list(range(1, 41)), (n, nos)
        assert test["meta"] == {"volume": 12, "testNo": n}
        assert test["durationMin"] == 32
        assert [s["audio"] for s in test["sections"]] == [f"ielts12_test{n}_audio{i}.mp3" for i in range(1, 5)]
    print({n: 40 for n in listening_tests()})
