# -*- coding: utf-8 -*-
"""CET-4 List 2 cards. Excel order; gaozhong field standard."""
from gaozhong_entry import numbered

ROWS = [
("device", "/dɪˈvaɪs/", "n.",
 "n. ①装置，设备，器具（a medical / electronic device）；②手段，策略（a rhetorical device）。leave to one's own devices（听任某人自行其是）。派生 devise（设计，想出）。",
 ["装置", "设备", "手段"],
 "electronic device（电子设备）, medical device（医疗器械）, a rhetorical device（修辞手法）",
 "The study tested a new device for monitoring blood pressure at home.", "该研究测试了一种可在家监测血压的新装置。",
 "de-（离开）+ vis（看）→ 想出来的东西 → 装置/策略",
 ["gadget", "tool"], [], "装置", "科技"),
("measure", "/ˈmeʒə(r)/ · /ˈmeʒər/", "n. / v.",
 "n. ①措施（take measures to do）；②计量单位；③程度（in large measure）。v. ①测量；②衡量。measurement（测量；尺寸）。beyond measure（无可估量）。",
 ["措施", "测量", "衡量"],
 "take measures（采取措施）, measure the impact（衡量影响）, in large measure（在很大程度上）",
 "The government has taken measures to reduce traffic in city centres.", "政府已采取措施减少市中心的交通流量。",
 "mens（测量）同源 → 量出尺寸，也指对策",
 ["step", "assess"], [], "措施", "社会"),
("pressure", "/ˈpreʃə(r)/ · /ˈpreʃər/", "n.",
 "n. ①压力（work / peer pressure；under pressure）；②压强；③催促。v. 对…施加压力（pressure sb into doing）。press（按；新闻界）。keep up the pressure。",
 ["压力", "压强", "催促"],
 "under pressure（在压力下）, peer pressure（同辈压力）, blood pressure（血压）",
 "Many graduates report high pressure in the first year of employment.", "许多毕业生表示，就业第一年压力很大。",
 "press（压）+ -ure → 压的状态 → 压力",
 ["stress"], ["relief"], "压力", "就业"),
("compare", "/kəmˈpeə(r)/ · /kəmˈper/", "v.",
 "v. ①比较（compare A with/to B）；②把…比作（compare A to B）。compared with/to（与…相比）。comparison（比较）；beyond compare（无与伦比）。comparable（可比的）。",
 ["比较", "相比", "比作"],
 "compare A with B（把A与B比较）, compared with（与…相比）, in comparison with（与…相比）",
 "The report compares rural schools with urban schools in terms of funding.", "该报告从经费方面比较了农村学校与城市学校。",
 "com-（一起）+ par（平等）→ 放在一起看是否相当",
 ["contrast"], [], "比较", "学术"),
("demand", "/dɪˈmɑːnd/ · /dɪˈmænd/", "n. / v.",
 "n. ①需求（demand for；in demand）；②要求。v. ①要求（demand that / to do）；②需要。supply and demand（供求）。demanding（要求高的）。语气强于 require。",
 ["需求", "要求", "需要"],
 "demand for（对…的需求）, in demand（有需求）, meet the demand（满足需求）",
 "There is a growing demand for graduates with data analysis skills.", "对具备数据分析能力的毕业生的需求在增长。",
 "de-（加强）+ mand（命令）→ 强求 → 要求/需求",
 ["request", "need"], ["supply"], "需求", "经济"),
("effort", "/ˈefət/ · /ˈefərt/", "n.",
 "n. ①努力，尽力（make an effort to do）；②费力的事；③努力的结果。effortless（不费力的）。joint / collective effort（共同努力）。in an effort to（为了）。",
 ["努力", "尽力"],
 "make an effort（努力）, in an effort to（为了）, joint effort（共同努力）",
 "The university made a considerable effort to improve student support services.", "该大学作出了相当大的努力来改善学生支持服务。",
 "ef-（出）+ fort（强）→ 使出力量 → 努力",
 ["attempt"], [], "努力", "校园"),
("material", "/məˈtɪəriəl/ · /məˈtɪriəl/", "n. / adj.",
 "n. ①材料，原料；②资料（reading / teaching materials，常用复数）；③衣料。adj. ①物质的；②重要的（material evidence）。materialism（物质主义）。",
 ["材料", "资料", "物质的"],
 "teaching materials（教材资料）, raw material（原材料）, material evidence（实质性证据）",
 "The course provides online materials to support independent study.", "该课程提供在线资料以支持自主学习。",
 "mater（物质/母体）+ -ial → 构成事物的材料",
 ["stuff", "substance"], [], "材料", "学术"),
("professional", "/prəˈfeʃənl/", "adj. / n.",
 "adj. ①职业的，专业的（professional development）；②内行的。n. 专业人士。profession（职业）；professor 勿混。unprofessional（不专业的）。",
 ["专业的", "职业的", "专业人士"],
 "professional development（专业发展）, professional skills（专业技能）, a medical professional（医疗专业人员）",
 "Professional development courses help teachers update their methods.", "专业发展课程帮助教师更新教学方法。",
 "profess（公开声称）+ -ion/-al → 以某业为志 → 专业的",
 ["expert"], ["amateur"], "专业的", "就业"),
("single", "/ˈsɪŋɡl/", "adj. / n.",
 "adj. ①单一的，单个的（a single parent；every single）；②单身的；③单人的。n. ①单身者；②单曲。single out（单独挑出）。反义 married / double。",
 ["单一的", "单个的", "单身的"],
 "a single parent（单亲）, every single（每一个）, single out（单独挑出）",
 "Not a single student completed the survey in less than ten minutes.", "没有一个学生能在十分钟内完成这份调查。",
 "sing（一）同源 → 一个的",
 ["only", "sole"], ["multiple", "married"], "单一的", "社会"),
("translation", "/trænsˈleɪʃn/ · /trænzˈleɪʃn/", "n.",
 "n. ①翻译，译文（a translation of）；②转化。in translation（在译本中）。动词 translate；translator（译者）。lost in translation（在翻译中丢失）。",
 ["翻译", "译文", "转化"],
 "a translation of（…的译本）, in translation（在译本中）, machine translation（机器翻译）",
 "Machine translation still makes errors in academic writing.", "机器翻译在学术写作中仍会出现错误。",
 "trans-（跨越）+ lat（拿）→ 从一边拿到另一边 → 翻译",
 ["version"], [], "翻译", "校园"),
("encourage", "/ɪnˈkʌrɪdʒ/ · /ɪnˈkɜːrɪdʒ/", "v.",
 "v. ①鼓励（encourage sb to do）；②促进，助长。encouragement（鼓励）；encouraging（令人鼓舞的）。反义 discourage。",
 ["鼓励", "促进", "助长"],
 "encourage sb to do（鼓励某人做）, encourage participation（鼓励参与）, an encouraging sign（令人鼓舞的迹象）",
 "Teachers are encouraged to give timely feedback on student essays.", "教师被鼓励及时对学生作文给出反馈。",
 "en-（使）+ courage（勇气）→ 使有勇气 → 鼓励",
 ["promote", "inspire"], ["discourage"], "鼓励", "教育"),
("factor", "/ˈfæktə(r)/ · /ˈfæktər/", "n.",
 "n. ①因素，要素（a key / risk factor）；②系数。factor in（把…考虑进去）。factor into（构成…的因素）。复数 factors。",
 ["因素", "要素", "系数"],
 "a key factor（关键因素）, risk factor（风险因素）, factor in（把…考虑进去）",
 "Sleep quality is a key factor in academic performance.", "睡眠质量是影响学业表现的一个关键因素。",
 "fact（做/制成）+ -or → 起作用的东西 → 因素",
 ["element"], [], "因素", "学术"),
("mental", "/ˈmentl/", "adj.",
 "adj. ①精神的，思想的（mental health / illness）；②智力的（mental ability）。mentally。与 physical 相对。mental arithmetic（心算）。",
 ["精神的", "心理的", "智力的"],
 "mental health（心理健康）, mental illness（精神疾病）, mental ability（智力）",
 "Universities have increased support for students' mental health.", "大学已加强对学生心理健康的支持。",
 "ment（心智）+ -al → 与心智有关的",
 ["psychological"], ["physical"], "心理的", "健康"),
("individual", "/ˌɪndɪˈvɪdʒuəl/", "n. / adj.",
 "adj. ①个人的，个体的（individual differences）；②独特的。n. 个人，个体。individually；individuality（个性）。反义 collective。",
 ["个人", "个体的", "独特的"],
 "individual differences（个体差异）, an individual（一个人）, individual rights（个人权利）",
 "The programme is designed to meet individual learning needs.", "该项目旨在满足个性化的学习需求。",
 "in-（不）+ divid（分割）+ -ual → 不可再分的单位 → 个体",
 ["personal"], ["collective"], "个人", "教育"),
("financial", "/faɪˈnænʃl/ · /fəˈnænʃl/", "adj.",
 "adj. ①财政的，金融的（financial support / crisis）；②财务的。finance（n. 财政；v. 资助）；financially。financial aid（助学金）。",
 ["财政的", "金融的", "财务的"],
 "financial support（资金支持）, financial crisis（金融危机）, financial aid（助学金）",
 "Financial support remains essential for students from low-income families.", "对来自低收入家庭的学生而言，资金支持仍然至关重要。",
 "finance（财政）+ -ial → 与钱有关的",
 ["economic"], [], "财政的", "经济"),
("involve", "/ɪnˈvɒlv/ · /ɪnˈvɑːlv/", "v.",
 "v. ①包含，需要（involve doing）；②使参与（involve sb in）；③牵涉。be involved in（参与；卷入）。involvement（参与）。involved（复杂的）。",
 ["包含", "涉及", "使参与"],
 "be involved in（参与；卷入）, involve doing（需要做…）, parental involvement（家长参与）",
 "The internship involves working with a research team for six weeks.", "这次实习需要与一个研究团队共事六周。",
 "in-（入）+ volve（卷）→ 卷进去 → 包含/牵涉",
 ["include", "entail"], [], "涉及", "学术"),
("leader", "/ˈliːdə(r)/ · /ˈliːdər/", "n.",
 "n. ①领导者，领袖（a team / political leader）；②领先者。leadership（领导；领导力）；leading（主要的，领先的）。lead（领导，不规则：led, led）。",
 ["领导者", "领袖", "领先者"],
 "team leader（组长）, leadership skills（领导力）, a leading cause（一个主要原因）",
 "The report examines the role of school leaders in educational reform.", "该报告探讨了学校领导者在教育改革中的作用。",
 "lead（带领）+ -er → 带领的人",
 ["head", "chief"], ["follower"], "领导者", "社会"),
("similar", "/ˈsɪmələ(r)/ · /ˈsɪmələr/", "adj.",
 "adj. 相似的，类似的（similar to，不接 with）。similarly。similarity（相似点）。反义 different / dissimilar。",
 ["相似的", "类似的"],
 "similar to（与…相似）, a similar pattern（类似的模式）, similarly（同样地）",
 "The two groups showed similar results after the training programme.", "两组在培训项目之后显示出相似的结果。",
 "simil（相同）+ -ar → 相近的",
 ["alike"], ["different"], "相似的", "学术"),
("detail", "/ˈdiːteɪl/ · /dɪˈteɪl/", "n. / v.",
 "n. ①细节，详情（in detail；go into detail）；②细部。v. 详述。detailed（详细的）。a detail of（一处细节）。",
 ["细节", "详情", "详述"],
 "in detail（详细地）, go into detail（详谈）, a detailed report（详细报告）",
 "The article describes the method in detail so that others can repeat it.", "文章详细描述了该方法，以便他人能够重复。",
 "de-（加强）+ tail（切割）→ 切得很细 → 细节",
 ["particular"], [], "细节", "学术"),
("expert", "/ˈekspɜːt/ · /ˈekspɜːrt/", "n. / adj.",
 "n. 专家（an expert in/on/at）。adj. 熟练的，内行的。expertise（专门知识）。expert opinion（专家意见）。",
 ["专家", "内行的", "熟练的"],
 "an expert in（…方面的专家）, expert opinion（专家意见）, expertise（专门知识）",
 "The panel included experts in public health and education policy.", "该小组包括公共卫生与教育政策方面的专家。",
 "ex-（出）+ pert（尝试）→ 经多次尝试而精通",
 ["specialist"], ["amateur"], "专家", "学术"),
("stress", "/stres/", "n. / v.",
 "n. ①精神压力（under stress；work stress）；②强调；③重音。v. ①强调（stress that / the importance of）；②使紧张。stressful。易混：pressure 偏外界压迫，stress 偏身心紧张。",
 ["压力", "强调", "重音"],
 "under stress（在压力下）, stress the importance of（强调…的重要性）, work stress（工作压力）",
 "The authors stress the importance of early intervention.", "作者强调早期干预的重要性。",
 "原义‘拉紧’，引申为精神上被拉紧",
 ["pressure", "emphasise"], [], "压力", "健康"),
("center/centre", "/ˈsentə(r)/ · /ˈsentər/", "n. / v.",
 "n. ①中心，中央（city centre，英式 centre；美式 center）；②中心机构（a research centre）。v. 集中（centre on/around）。central（中心的）。Excel 词形并存，例句用英式 centre。",
 ["中心", "中央", "中心机构"],
 "city centre（市中心）, research centre（研究中心）, centre on（以…为中心）",
 "A new research centre has been set up to study air quality.", "已设立一个新的研究中心来研究空气质量。",
 "centr（中心）→ 位于正中的点或机构",
 ["middle", "hub"], ["edge"], "中心", "学术"),
("gender", "/ˈdʒendə(r)/ · /ˈdʒendər/", "n.",
 "n. ①性别（gender differences / equality）；②（语法）性。gender gap（性别差距）。与 sex 相比，gender 更多指社会文化角色。",
 ["性别", "社会性别"],
 "gender equality（性别平等）, gender differences（性别差异）, gender gap（性别差距）",
 "The study found a persistent gender gap in science careers.", "该研究发现，科学职业中的性别差距依然存在。",
 "genus（种类）同源 → 类别 → 性别",
 ["sex"], [], "性别", "社会"),
("medium", "/ˈmiːdiəm/", "n. / adj.",
 "n. ①媒介，手段（a medium of communication）；②媒体（the media，复数常用）；③中间。adj. 中等的（medium-sized）。medium term（中期）。",
 ["媒介", "媒体", "中等的"],
 "the media（媒体）, a medium of（…的媒介）, medium-sized（中等规模的）",
 "Social media have become an important medium of public debate.", "社交媒体已成为公共讨论的重要媒介。",
 "med（中间）+ -ium → 处于中间的渠道",
 ["means", "channel"], [], "媒介", "社会"),
("rate", "/reɪt/", "n. / v.",
 "n. ①比率，速率（growth / unemployment rate）；②费用，价格；③等级。v. 评价，列为（rate as）。at a rate of。the rate at which…。",
 ["比率", "速率", "评价"],
 "unemployment rate（失业率）, at a rate of（以…的速度）, growth rate（增长率）",
 "The unemployment rate remained high among recent graduates.", "应届毕业生中的失业率仍然很高。",
 "rat（计算）+ -e → 算出的比例",
 ["ratio", "speed"], [], "比率", "经济"),
("available", "/əˈveɪləbl/", "adj.",
 "adj. ①可获得的，可用的（available to/for）；②有空的。availability（可获得性）。make sth available。反义 unavailable。",
 ["可获得的", "可用的", "有空的"],
 "available to（可供…使用）, make available（提供）, availability（可获得性）",
 "Scholarships are available to students from rural areas.", "奖学金可供农村地区的学生申请。",
 "a-（向）+ vail（价值/益处）→ 拿得到好处的 → 可获得的",
 ["accessible"], ["unavailable"], "可获得的", "教育"),
("unite", "/juˈnaɪt/", "v.",
 "v. ①联合，团结（unite to do / against）；②统一。united（联合的，团结的）；union（联盟；工会）；unity（团结，统一）。the United Kingdom。",
 ["联合", "团结", "统一"],
 "unite to（联合起来做）, united effort（共同努力）, political union（政治联盟）",
 "European countries united to address the energy shortage.", "欧洲国家联合起来应对能源短缺。",
 "uni-（一）+ -ite → 使成为一体",
 ["join", "combine"], ["divide"], "联合", "社会"),
("attack", "/əˈtæk/", "n. / v.",
 "n. ①攻击，袭击（an attack on）；②抨击；③（疾病）发作（a heart attack）。v. 攻击，抨击。under attack。attacker。",
 ["攻击", "袭击", "抨击"],
 "an attack on（对…的攻击/抨击）, heart attack（心脏病发作）, under attack（受到攻击）",
 "The policy came under attack from several education experts.", "该政策受到几位教育专家的抨击。",
 "at-（向）+ tach/tack（接触）→ 扑向 → 攻击",
 ["assault"], ["defend"], "攻击", "社会"),
("potential", "/pəˈtenʃl/", "n. / adj.",
 "n. 潜力，可能性（the potential to do / for）。adj. 潜在的（potential risks）。potentially。realise one's potential（发挥潜力，英式 realise）。",
 ["潜力", "潜在的", "可能性"],
 "potential risks（潜在风险）, the potential to（有…的潜力）, realise one's potential（发挥潜力）",
 "Online courses have the potential to widen access to higher education.", "在线课程有潜力扩大高等教育的入学机会。",
 "potent（有力的）+ -ial → 尚未发挥的力量",
 ["possibility"], [], "潜力", "教育"),
("video", "/ˈvɪdiəʊ/ · /ˈvɪdioʊ/", "n.",
 "n. ①视频，录像（a video clip / recording）；②录像节目。v. 给…录像。video conferencing（视频会议）。复数 videos。",
 ["视频", "录像"],
 "video clip（视频片段）, video conferencing（视频会议）, instructional video（教学录像）",
 "The lecture was recorded as a video for students who could not attend.", "该讲座被录成视频，供无法到场的学生观看。",
 "vid（看）+ -eo → 能看见的影像",
 ["film", "recording"], [], "视频", "科技"),
("account", "/əˈkaʊnt/", "n. / v.",
 "n. ①账户（bank account）；②叙述，报道（an account of）；③考虑（take into account）。v. 解释（account for 解释；占…比例）。on account of（因为）。",
 ["账户", "叙述", "解释"],
 "take into account（考虑到）, account for（解释；占…）, bank account（银行账户）",
 "Teachers should take individual differences into account when marking essays.", "教师在批改作文时应考虑到个体差异。",
 "ac-（向）+ count（计算）→ 算清楚 → 账目/说明",
 ["report", "explain"], [], "账户", "学术"),
("engage", "/ɪnˈɡeɪdʒ/", "v.",
 "v. ①从事，参加（engage in）；②吸引（engage sb's attention）；③雇用；④订婚（be engaged to）。engagement（参与；订婚）；engaging（引人入胜的）。",
 ["从事", "参与", "吸引"],
 "engage in（从事；参与）, student engagement（学生参与）, engage attention（吸引注意）",
 "The course is designed to engage students in independent research.", "该课程旨在让学生参与独立研究。",
 "en-（使）+ gage（抵押/约束）→ 使卷入 → 从事/吸引",
 ["participate", "involve"], [], "参与", "教育"),
("prove", "/pruːv/", "v.",
 "v. ①证明（prove that / to be）；②结果是，原来是（prove difficult）。proof（证据）；proven / proved（过去分词皆可）。反义 disprove。",
 ["证明", "证实", "原来是"],
 "prove that（证明…）, prove to be（结果是）, scientific proof（科学证据）",
 "Further studies are needed to prove the long-term effects of the policy.", "还需要进一步研究来证明该政策的长期效果。",
 "与 proof 同源 → 拿出证据",
 ["demonstrate", "show"], ["disprove"], "证明", "学术"),
("effective", "/ɪˈfektɪv/", "adj.",
 "adj. ①有效的（effective in / at）；②实际的，生效的（effective from）。effectiveness。易混 efficient（效率高的，省时省力）。effect（n. 效果）。",
 ["有效的", "生效的", "实际的"],
 "effective in（在…方面有效）, take effect（生效）, an effective method（有效方法）",
 "Feedback is more effective when it is specific and timely.", "反馈在具体且及时时更为有效。",
 "effect（效果）+ -ive → 能产生效果的",
 ["successful"], ["ineffective"], "有效的", "学术"),
("increasingly", "/ɪnˈkriːsɪŋli/", "adv.",
 "adv. 越来越多地，日益（increasingly important / common）。increase（v./n. 增加）；increasing。用于描述趋势，常修饰形容词。",
 ["越来越", "日益", "逐渐增加地"],
 "increasingly important（日益重要）, increasingly common（越来越普遍）, an increasing number of（越来越多的）",
 "Remote work has become increasingly common in the service sector.", "远程办公在服务业中已变得越来越普遍。",
 "increase（增加）+ -ing + -ly → 正在增加地",
 ["more and more"], ["decreasingly"], "越来越", "社会"),
("trend", "/trend/", "n.",
 "n. 趋势，倾向（a trend towards / in）。v. 倾向，趋向（较少考）。trendy（时髦的）。follow / reverse a trend。current trends。",
 ["趋势", "倾向", "潮流"],
 "a trend towards（朝…的趋势）, current trends（当前趋势）, follow the trend（跟随潮流）",
 "There is a clear trend towards later marriage in large cities.", "大城市中晚婚趋势十分明显。",
 "原义‘旋转/走向’，引申为发展方向",
 ["tendency"], [], "趋势", "社会"),
("apply", "/əˈplaɪ/", "v.",
 "v. ①申请（apply for / to）；②应用（apply A to B）；③适用（apply to）。application（申请；应用）；applicant（申请人）；applied（应用的）。",
 ["申请", "应用", "适用"],
 "apply for（申请）, apply to（适用于；向…申请）, application form（申请表）",
 "More than two thousand students applied for the scholarship last year.", "去年有两千多名学生申请该项奖学金。",
 "ap-（向）+ ply（折叠/用）→ 把…用到某处",
 ["request", "use"], [], "申请", "校园"),
("billion", "/ˈbɪljən/", "n. / num.",
 "n. / num. 十亿（美式及当代英式；旧英式 billion 曾指万亿，四级按十亿理解）。billions of（数十亿的）。billionaire（亿万富翁）。",
 ["十亿", "十亿的"],
 "billions of（数十亿的）, two billion people（二十亿人）, a billion dollars（十亿美元）",
 "The company invested two billion pounds in renewable energy.", "该公司在可再生能源上投资了二十亿英镑。",
 "bi- 在此不表‘二’，现代用法固定为 10^9",
 ["a thousand million"], [], "十亿", "经济"),
("attract", "/əˈtrækt/", "v.",
 "v. ①吸引（attract attention / investment）；②招引。attraction（吸引力；景点）；attractive（有吸引力的）。be attracted to。",
 ["吸引", "招引"],
 "attract attention（引起注意）, attract investment（吸引投资）, tourist attraction（旅游景点）",
 "The new campus has attracted students from more than thirty countries.", "新校区吸引了来自三十多个国家的学生。",
 "at-（向）+ tract（拉）→ 拉过来 → 吸引",
 ["draw", "appeal to"], ["repel"], "吸引", "教育"),
("evidence", "/ˈevɪdəns/", "n.",
 "n. 证据，证明（evidence of / that / for；不可数）。v. 证明（较正式）。evident（明显的）。there is evidence that…。in evidence（显而易见）。",
 ["证据", "证明", "根据"],
 "evidence that（证明…的证据）, there is evidence that（有证据表明）, scientific evidence（科学证据）",
 "There is growing evidence that sleep affects memory.", "越来越多的证据表明，睡眠影响记忆。",
 "e-（出）+ vid（看）→ 能看出来的东西 → 证据",
 ["proof"], [], "证据", "学术"),
("female", "/ˈfiːmeɪl/", "adj. / n.",
 "adj. 女的，雌的（female students / workers）。n. 女子，雌性。与 male 相对。书面语中作形容词修饰名词最常见。feminine 偏指女性气质。",
 ["女的", "雌的", "女子"],
 "female students（女生）, female workers（女工）, male and female（男女）",
 "Female students now outnumber male students in several arts subjects.", "在若干文科专业中，女生人数已超过男生。",
 "与 male 成对；fe- 不表‘铁’",
 ["woman"], ["male"], "女的", "社会"),
("owner", "/ˈəʊnə(r)/ · /ˈoʊnər/", "n.",
 "n. 所有者，物主（the owner of）。own（v. 拥有；adj. 自己的）；ownership（所有权）。homeowner（房主）。",
 ["所有者", "物主", "主人"],
 "the owner of（…的所有者）, car owner（车主）, ownership（所有权）",
 "The owner of the factory agreed to reduce night-time noise.", "工厂所有者同意减少夜间噪音。",
 "own（拥有）+ -er → 拥有者",
 ["holder"], [], "所有者", "经济"),
("reward", "/rɪˈwɔːd/ · /rɪˈwɔːrd/", "n. / v.",
 "n. ①报酬，奖赏（a reward for）；②回报。v. 奖励，报答（reward sb for）。rewarding（有益的，值得的）。易混 award（颁发奖项）。",
 ["报酬", "奖赏", "回报"],
 "a reward for（对…的奖赏）, reward sb for（因…奖励某人）, a rewarding job（有意义的工作）",
 "Teaching can be a rewarding career despite the heavy workload.", "尽管工作量大，教学仍可以是一份有回报的职业。",
 "re-（回）+ ward（看护）→ 回过来给予 → 回报",
 ["prize", "pay"], ["punishment"], "回报", "就业"),
("current", "/ˈkʌrənt/ · /ˈkɜːrənt/", "adj. / n.",
 "adj. ①当前的，现在的（current research / affairs）；②流通的。n. ①水流，气流；②电流；③潮流。currently。curriculum 勿混。",
 ["当前的", "电流", "潮流"],
 "current research（当前研究）, current affairs（时事）, electric current（电流）",
 "Current research suggests that exercise improves concentration.", "当前研究表明，锻炼能提高注意力。",
 "curr（跑）+ -ent → 正在流/跑着的 → 当前的/流",
 ["present"], ["former"], "当前的", "学术"),
("male", "/meɪl/", "adj. / n.",
 "adj. 男的，雄的（male students / animals）。n. 男子，雄性。与 female 相对。masculine 偏指男性气质。mail（邮件）仅拼写相近。",
 ["男的", "雄的", "男子"],
 "male students（男生）, male and female（男女）, male workers（男工）",
 "The sample included both male and female participants aged 18 to 25.", "样本包括 18 至 25 岁的男性和女性参与者。",
 "与 female 成对，表生物性别",
 ["man"], ["female"], "男的", "社会"),
("relate", "/rɪˈleɪt/", "v.",
 "v. ①有关联（relate to）；②讲述；③相处（relate to sb）。related（有关的）；relation（关系）；relationship（人际关系）。be related to。",
 ["有关", "涉及", "讲述"],
 "relate to（与…有关；理解）, be related to（与…相关）, in relation to（关于）",
 "The findings relate to a wider debate about online learning.", "这些发现关系到关于在线学习的更广泛讨论。",
 "re-（回）+ lat（拿）→ 把事物拿回来对照 → 关联",
 ["connect"], ["unrelated"], "有关", "学术"),
("solve", "/sɒlv/ · /sɑːlv/", "v.",
 "v. 解决，解答（solve a problem / puzzle）。solution（解决办法；溶液）。solvable。solve 后直接接问题，不接 to。",
 ["解决", "解答"],
 "solve a problem（解决问题）, find a solution（找到解决办法）, solve a puzzle（解谜）",
 "The committee met to solve the shortage of student accommodation.", "委员会开会以解决学生住宿短缺问题。",
 "solv（松开）→ 把结解开 → 解决",
 ["resolve"], [], "解决", "社会"),
("action", "/ˈækʃn/", "n.",
 "n. ①行动，行为（take action）；②作用；③诉讼。in action（在运转；在起作用）。active；activity。take action to do。",
 ["行动", "行为", "作用"],
 "take action（采取行动）, in action（在起作用）, legal action（法律诉讼）",
 "The government promised to take action against food waste.", "政府承诺对食物浪费采取行动。",
 "act（做）+ -ion → 做出来的事 → 行动",
 ["act", "measure"], [], "行动", "社会"),
("bacteria", "/bækˈtɪəriə/ · /bækˈtɪriə/", "n.",
 "n. 细菌（bacterium 的复数；作主语时动词常用复数）。bacterial（细菌的）。beneficial / harmful bacteria。勿与 virus（病毒）混用。",
 ["细菌", "病菌"],
 "harmful bacteria（有害细菌）, bacterial infection（细菌感染）, antibiotic-resistant bacteria（耐药细菌）",
 "Some bacteria in the gut are essential for digestion.", "肠道中的一些细菌对消化至关重要。",
 "bacter（小棒）→ 杆状微生物 → 细菌",
 ["germs"], [], "细菌", "健康"),
("marry", "/ˈmæri/", "v.",
 "v. ①结婚（marry sb，不接 with）；②把…嫁给。get married（结婚，状态/动作皆可）。marriage（婚姻）；married。marry in/into。",
 ["结婚", "嫁", "娶"],
 "get married（结婚）, marry sb（与某人结婚）, marriage rate（结婚率）",
 "The average age at which people marry has risen over the past decade.", "过去十年里，人们结婚的平均年龄有所上升。",
 "与 marriage 同源，指结成夫妇",
 ["wed"], ["divorce"], "结婚", "社会"),
("recently", "/ˈriːsntli/", "adv.",
 "adv. 最近，近来（与现在完成时或一般过去时连用）。recent（最近的）。as recently as（就在最近…时）。",
 ["最近", "近来"],
 "until recently（直到最近）, as recently as（就在最近）, a recent study（一项近期研究）",
 "A recent study has shown that short breaks improve concentration.", "一项近期研究表明，短暂休息能提高注意力。",
 "recent（新近的）+ -ly",
 ["lately"], [], "最近", "学术"),
("balance", "/ˈbæləns/", "n. / v.",
 "n. ①平衡（keep a balance between A and B）；②余额；③天平。v. 使平衡。on balance（总的来说）。balanced（均衡的）。work–life balance。",
 ["平衡", "余额", "使平衡"],
 "keep a balance（保持平衡）, work–life balance（工作与生活的平衡）, on balance（总的来说）",
 "Students need to keep a balance between study and rest.", "学生需要在学习与休息之间保持平衡。",
 "原指天平两臂，引申为两边相当",
 ["equilibrium"], ["imbalance"], "平衡", "校园"),
("replace", "/rɪˈpleɪs/", "v.",
 "v. ①替换（replace A with/by B）；②取代；③把…放回原处。replacement（替换；替代物）。in place of。",
 ["替换", "取代", "放回"],
 "replace A with B（用B替换A）, replacement（替代物）, in place of（代替）",
 "Online materials will not completely replace printed textbooks.", "在线资料不会完全取代纸质教材。",
 "re-（再）+ place（放置）→ 放到原位/换成另一个",
 ["substitute"], [], "替换", "教育"),
("charge", "/tʃɑːdʒ/ · /tʃɑːrdʒ/", "n. / v.",
 "n. ①费用（free of charge）；②指控；③主管（in charge of）；④电荷。v. ①收费；②指控（charge sb with）；③充电。take charge of。",
 ["收费", "指控", "主管"],
 "in charge of（负责）, free of charge（免费）, charge sb with（指控某人）",
 "A senior lecturer is in charge of the writing programme.", "一位资深讲师负责该写作项目。",
 "原义‘装上负担’→ 收费/指控/充电",
 ["fee", "accuse"], [], "负责", "校园"),
("facility", "/fəˈsɪləti/", "n.",
 "n. ①设施，设备（sports / medical facilities，常用复数）；②便利，才能。facilitate（使便利）。research facilities。",
 ["设施", "设备", "便利"],
 "sports facilities（体育设施）, medical facilities（医疗设施）, research facilities（研究设施）",
 "The new campus provides excellent sports facilities for students.", "新校区为学生提供了很好的体育设施。",
 "facil（容易）+ -ity → 使事情容易进行的条件 → 设施",
 ["amenities"], [], "设施", "校园"),
("influence", "/ˈɪnfluəns/", "n. / v.",
 "n. 影响（influence on/over；under the influence of）。v. 影响（influence sb/sth，不接 on）。influential（有影响力的）。比 affect 更可作名词。",
 ["影响", "影响力"],
 "influence on（对…的影响）, under the influence of（在…影响下）, an influential study（一项有影响力的研究）",
 "Peer influence on study habits is often stronger than teachers expect.", "同伴对学习习惯的影响往往比教师预期的更强。",
 "in-（入）+ flu（流）→ 流入而起作用 → 影响",
 ["affect", "impact"], [], "影响", "教育"),
("policy", "/ˈpɒləsi/ · /ˈpɑːləsi/", "n.",
 "n. ①政策（education / economic policy）；②方针；③保险单（an insurance policy）。policy on/towards。policy-maker。",
 ["政策", "方针", "保险单"],
 "education policy（教育政策）, economic policy（经济政策）, insurance policy（保险单）",
 "The new education policy aims to reduce the cost of textbooks.", "新的教育政策旨在降低教材费用。",
 "polis（城邦）同源 → 治理城邦的办法 → 政策",
 ["strategy"], [], "政策", "社会"),
("argue", "/ˈɑːɡjuː/ · /ˈɑːrɡjuː/", "v.",
 "v. ①主张，认为（argue that，学术高频）；②争论（argue with sb about）；③论证。argument（论点；争论）；argumentative。argue for/against。",
 ["主张", "争论", "论证"],
 "argue that（认为…）, argue for（主张支持）, an argument（论点；争论）",
 "The authors argue that smaller classes improve writing quality.", "作者认为，较小的班级能提高写作质量。",
 "argu（澄清）→ 把道理说清楚 → 论证/争论",
 ["claim", "maintain"], [], "主张", "学术"),
("contribute", "/kənˈtrɪbjuːt/", "v.",
 "v. ①促成，导致（contribute to，不接 to doing 而接名词/动名词皆可见）；②捐献，投稿。contribution（贡献）；contributor。a contributing factor。",
 ["促成", "贡献", "捐献"],
 "contribute to（促成；贡献于）, make a contribution（作出贡献）, a contributing factor（促成因素）",
 "Lack of sleep may contribute to poorer exam performance.", "睡眠不足可能导致考试成绩较差。",
 "con-（共同）+ tribute（给予）→ 一起给出 → 贡献/促成",
 ["lead to", "donate"], [], "促成", "学术"),
("generally", "/ˈdʒenrəli/", "adv.",
 "adv. ①一般来说，通常（it is generally believed that）；②普遍地。general（一般的；将军）；in general。generalisation（概括，英式 -isation）。",
 ["一般来说", "通常", "普遍地"],
 "in general（一般来说）, it is generally believed that（人们普遍认为）, generally speaking（一般而言）",
 "It is generally believed that regular review improves long-term memory.", "人们普遍认为，定期复习能改善长期记忆。",
 "general（一般的）+ -ly",
 ["usually", "broadly"], [], "一般来说", "学术"),
("hire", "/ˈhaɪə(r)/ · /ˈhaɪər/", "v. / n.",
 "v. ①雇用（hire sb）；②租用（英式 hire a car，美式常用 rent）。n. 雇用，租用（for hire）。hire out。hirer。与 fire（解雇）相对。",
 ["雇用", "租用"],
 "hire sb（雇用某人）, hire a car（租车）, for hire（供租用）",
 "The laboratory hired two research assistants for the project.", "该实验室为这个项目雇用了两名研究助理。",
 "原义‘工资’，引申为付钱用人或用物",
 ["employ", "rent"], ["fire"], "雇用", "就业"),
("knit", "/nɪt/", "v.",
 "v. ①编织，针织（knit a sweater）；②使紧密结合（knit together）。n. 针织衫。close-knit（紧密团结的）。过去式 knitted 或 knit。",
 ["编织", "针织", "结合"],
 "knit together（使紧密结合）, a close-knit community（紧密团结的社区）, knit a sweater（织毛衣）",
 "The programme aims to knit together researchers from different faculties.", "该项目旨在把不同院系的研究者紧密联系起来。",
 "原义‘用线连结’，引申为使群体结合",
 ["weave", "join"], [], "编织", "社会"),
("various", "/ˈveəriəs/ · /ˈveriəs/", "adj.",
 "adj. 各种各样的（various reasons / methods）。variety（多样性；种类）；a variety of；vary（变化）；variation。比 different 更强调‘多种’。",
 ["各种各样的", "不同的"],
 "various reasons（种种原因）, a variety of（各种各样的）, vary from（与…不同）",
 "The survey listed various reasons why students drop out.", "该调查列出了学生退学的种种原因。",
 "vari（变化）+ -ous → 多变化的 → 各种各样的",
 ["diverse", "several"], ["single"], "各种各样的", "学术"),
("contact", "/ˈkɒntækt/ · /ˈkɑːntækt/", "n. / v.",
 "n. ①接触，联系（in contact with；make contact with）；②熟人。v. 联系（contact sb，不接 with）。contact details（联系方式）。",
 ["联系", "接触", "联络"],
 "in contact with（与…保持联系）, contact sb（联系某人）, contact details（联系方式）",
 "Students were asked to contact their supervisor once a week.", "学生被要求每周与导师联系一次。",
 "con-（共同）+ tact（触）→ 碰到一起 → 接触/联系",
 ["touch", "reach"], [], "联系", "校园"),
("resource", "/rɪˈsɔːs/ · /ˈriːsɔːrs/", "n.",
 "n. ①资源（natural / educational resources，常用复数）；②资料。resourceful（足智多谋的）。human resources（人力资源）。",
 ["资源", "资料"],
 "natural resources（自然资源）, educational resources（教育资源）, human resources（人力资源）",
 "Not all schools have equal access to digital learning resources.", "并非所有学校都能平等获得数字化学习资源。",
 "re-（再）+ source（来源）→ 可一再取用的来源",
 ["supply"], [], "资源", "教育"),
("supply", "/səˈplaɪ/", "n. / v.",
 "n. ①供应，供给（in short supply；water supply）；②补给（supplies）。v. 供给（supply sb with sth / supply sth to sb）。supply and demand。",
 ["供应", "供给", "补给"],
 "in short supply（供应不足）, water supply（供水）, supply sb with（向某人提供）",
 "Clean water was in short supply after the storm.", "风暴过后，清洁用水供应不足。",
 "sup-（从下）+ ply（填满）→ 补上 → 供给",
 ["provide"], ["demand"], "供应", "社会"),
("credit", "/ˈkredɪt/", "n. / v.",
 "n. ①学分（course credits）；②信用，信贷（credit card）；③赞扬（give sb credit for）。v. ①记入贷方；②认为…有（credit sb with）。to sb's credit。",
 ["学分", "信用", "赞扬"],
 "credit card（信用卡）, course credits（课程学分）, give sb credit for（因…赞扬某人）",
 "Students must complete 120 credits before they can graduate.", "学生须修满 120 个学分才能毕业。",
 "cred（相信）+ -it → 被相信的额度 → 信用/学分",
 ["recognition"], [], "学分", "校园"),
("airport", "/ˈeəpɔːt/ · /ˈerpɔːrt/", "n.",
 "n. 机场（at the airport；an international airport）。air + port（港）。airport security。复数 airports。",
 ["机场", "航空港"],
 "at the airport（在机场）, international airport（国际机场）, airport security（机场安检）",
 "A new railway line will connect the city centre with the airport.", "一条新铁路线将把市中心与机场连接起来。",
 "air（空中）+ port（港口）→ 空中港口",
 ["airfield"], [], "机场", "交通"),
("interview", "/ˈɪntəvjuː/ · /ˈɪntərvjuː/", "n. / v.",
 "n. ①面试（a job interview）；②采访。v. 面试，采访（interview sb for / about）。interviewee；interviewer。in an interview。",
 ["面试", "采访"],
 "job interview（求职面试）, interview sb（采访/面试某人）, in an interview（在采访中）",
 "Candidates were interviewed for twenty minutes about their research plans.", "候选人就其研究计划接受了二十分钟的面试。",
 "inter-（在…之间）+ view（看）→ 当面相看 → 面试/采访",
 ["meeting"], [], "面试", "就业"),
("solar", "/ˈsəʊlə(r)/ · /ˈsoʊlər/", "adj.",
 "adj. ①太阳的（solar energy / power）；②太阳能的。solar panel（太阳能电池板）。solar system（太阳系）。与 lunar（月亮的）相对。",
 ["太阳的", "太阳能的"],
 "solar energy（太阳能）, solar power（太阳能发电）, solar panel（太阳能电池板）",
 "Several universities have invested in solar energy on campus.", "若干大学已在校园内投资太阳能。",
 "sol（太阳）+ -ar → 与太阳有关的",
 [], ["lunar"], "太阳的", "环境"),
("mobile", "/ˈməʊbaɪl/ · /ˈmoʊbl/", "adj. / n.",
 "adj. ①可移动的（a mobile population）；②流动的。n. 手机（英式 a mobile；美式 cell phone）。mobile phone。mobility（流动性）。immobilise（使不能移动）。",
 ["可移动的", "手机", "流动的"],
 "mobile phone（手机）, a mobile population（流动人口）, social mobility（社会流动性）",
 "Mobile phones are now widely used for language learning.", "手机现已广泛用于语言学习。",
 "mov（移动）同源 → 可移动的；英式名词指手机",
 ["portable"], ["fixed"], "可移动的", "科技"),
("promote", "/prəˈməʊt/ · /prəˈmoʊt/", "v.",
 "v. ①促进，推动（promote growth / health）；②促销；③晋升（be promoted to）。promotion（促进；促销；晋升）；promotional。",
 ["促进", "推销", "晋升"],
 "promote growth（促进增长）, be promoted to（被提升为）, health promotion（健康促进）",
 "The campaign aims to promote reading among primary school children.", "该活动旨在促进小学生阅读。",
 "pro-（向前）+ mote（移动）→ 向前推 → 促进/晋升",
 ["encourage", "advance"], [], "促进", "教育"),
("shift", "/ʃɪft/", "n. / v.",
 "n. ①转变（a shift in / towards）；②轮班（night shift）。v. 转移，改变（shift from A to B）。shift work。make a shift。",
 ["转变", "转移", "轮班"],
 "a shift in（在…方面的转变）, night shift（夜班）, shift from A to B（从A转向B）",
 "There has been a shift towards online assessment in higher education.", "高等教育已出现转向在线测评的趋势。",
 "原义‘分开/更换位置’→ 转变/换班",
 ["change", "move"], [], "转变", "教育"),
("accident", "/ˈæksɪdənt/", "n.",
 "n. ①事故（a traffic / car accident）；②意外。by accident（偶然，= by chance）。accidental（意外的）。accident and emergency（急诊）。",
 ["事故", "意外", "偶然"],
 "by accident（偶然）, traffic accident（交通事故）, accidental（意外的）",
 "The decline in traffic accidents followed stricter speed limits.", "交通事故的减少出现在更严格的限速规定之后。",
 "ac-（向）+ cid（落）→ 落到头上 → 意外",
 ["crash", "mishap"], [], "事故", "社会"),
("management", "/ˈmænɪdʒmənt/", "n.",
 "n. ①管理，经营（time / waste management）；②管理层（the management）。manage（管理）；manager（经理）；manageable。management skills。",
 ["管理", "经营", "管理层"],
 "time management（时间管理）, waste management（废物管理）, management skills（管理技能）",
 "Time management is often cited as a key skill for university students.", "时间管理常被列为大学生的一项关键技能。",
 "manage（驾驭）+ -ment → 驾驭事务 → 管理",
 ["administration"], [], "管理", "校园"),
("source", "/sɔːs/ · /sɔːrs/", "n.",
 "n. ①来源，出处（a source of energy / information）；②消息来源；③源头。v. 采购，寻求来源。primary source（第一手资料）。source material。",
 ["来源", "出处", "源头"],
 "a source of（…的来源）, primary source（第一手资料）, energy source（能源）",
 "The internet is now a major source of health information for young people.", "互联网现已成为年轻人获取健康信息的一个主要来源。",
 "与 surge（涌出）同源 → 涌出之处 → 来源",
 ["origin"], [], "来源", "学术"),
("option", "/ˈɒpʃn/ · /ˈɑːpʃn/", "n.",
 "n. ①选择，选项（have no option but to）；②选修课。optional（可选择的）。the best option。keep one's options open。",
 ["选择", "选项", "选修"],
 "have no option but to（别无选择只能）, optional course（选修课）, the best option（最佳选择）",
 "Part-time work is one option for students who need extra income.", "兼职工作是需要额外收入的学生的一个选择。",
 "opt（选择）+ -ion → 选出来的路",
 ["choice", "alternative"], [], "选择", "校园"),
("purchase", "/ˈpɜːtʃəs/ · /ˈpɜːrtʃəs/", "n. / v.",
 "n. 购买，购得物（make a purchase）。v. 购买（较 buy 正式）。purchasing power（购买力）。purchaser。",
 ["购买", "采购", "购得物"],
 "make a purchase（购买）, purchasing power（购买力）, purchase online（网上购买）",
 "Consumers' purchasing power has declined because of higher housing costs.", "由于住房成本上升，消费者的购买力已经下降。",
 "pur-（向前）+ chase（追求）→ 追着去买 → 购买",
 ["buy"], ["sell"], "购买", "经济"),
("function", "/ˈfʌŋkʃn/", "n. / v.",
 "n. ①功能，作用（the function of）；②典礼，宴会。v. 运转，起作用（function as / normally）。functional（实用的；功能的）。functioning。",
 ["功能", "作用", "运转"],
 "the function of（…的功能）, function as（起…的作用）, function normally（正常运转）",
 "The committee functions as an advisory body for the university.", "该委员会作为大学的顾问机构发挥作用。",
 "fung（履行）+ -tion → 所履行的职责 → 功能",
 ["role", "work"], [], "功能", "学术"),
("panel", "/ˈpænl/", "n.",
 "n. ①专门小组（an expert panel；a panel of judges）；②面板，嵌板；③仪表盘。panel discussion（小组讨论）。solar panel。",
 ["小组", "面板", "仪表盘"],
 "expert panel（专家小组）, panel discussion（小组讨论）, solar panel（太阳能电池板）",
 "An expert panel was invited to review the new curriculum.", "邀请了一个专家小组来评审新的课程方案。",
 "原义‘一块布/板’，引申为坐在一块的评审组",
 ["board", "committee"], [], "小组", "学术"),
("outside", "/ˌaʊtˈsaɪd/", "prep. / adv. / n. / adj.",
 "prep. / adv. 在…外面（outside the classroom；英式少用 outside of）。n. 外面，外部。adj. 外面的，外界的（outside help）。outsider（局外人）。反义 inside。",
 ["外面", "在外面", "外部的"],
 "outside the classroom（在课堂外）, outside help（外界帮助）, on the outside（在外面）",
 "Learning also takes place outside the classroom, for example in internships.", "学习也发生在课堂之外，例如在实习中。",
 "out + side → 在某一侧之外",
 ["outdoors"], ["inside"], "外面", "教育"),
]

assert len(ROWS) == 81
WORDS = numbered(ROWS)
assert [w["word"] for w in WORDS] == [r[0] for r in ROWS]


def cet4_words():
    return [dict(w) for w in WORDS]


if __name__ == "__main__":
    from inject_cet4 import write_list
    write_list(2, cet4_words(), excel=[r[0] for r in ROWS])
