# -*- coding: utf-8 -*-
"""CET-4 List 3 cards. Excel order; gaozhong field standard."""
from gaozhong_entry import numbered

ROWS = [
("particularly", "/pəˈtɪkjələli/ · /pərˈtɪkjələrli/", "adv.",
 "adv. ①尤其，特别（particularly important / in）；②格外地。particular（特定的；挑剔的）；in particular（尤其）。语气强于 especially 的书面用法相近。",
 ["尤其", "特别", "格外"],
 "particularly important（尤其重要）, in particular（尤其）, be particular about（对…挑剔）",
 "Air pollution is particularly harmful to children and the elderly.", "空气污染对儿童和老年人尤其有害。",
 "particular（特定的）+ -ly → 就特定方面而言 → 尤其",
 ["especially"], ["generally"], "尤其", "学术"),
("saving", "/ˈseɪvɪŋ/", "n. / adj.",
 "n. ①节省，节约（a saving of）；②存款（savings，常用复数）。adj. 节约的。save（节省；拯救）。saving account 宜作 savings account。",
 ["节省", "存款", "节约"],
 "savings account（储蓄账户）, a saving of（节省了…）, energy saving（节能）",
 "Energy-saving measures led to a 15 per cent saving on electricity bills.", "节能措施使电费节省了百分之十五。",
 "save（节省）+ -ing → 省下来的钱或行为",
 ["economy"], ["spending"], "节省", "经济"),
("ancient", "/ˈeɪnʃənt/", "adj.",
 "adj. ①古代的（ancient history / civilisation，英式 -isation）；②古老的。the ancients（古人）。反义 modern。比 old 更强调久远历史。",
 ["古代的", "古老的"],
 "ancient history（古代史）, ancient civilisation（古代文明）, ancient times（古代）",
 "The museum exhibition focuses on ancient civilisation in the Mediterranean.", "该博物馆展览聚焦地中海地区的古代文明。",
 "ante（在前）同源 → 很久以前的",
 ["old"], ["modern"], "古代的", "学术"),
("calorie", "/ˈkæləri/", "n.",
 "n. 卡路里，热量单位（calorie intake；low-calorie）。复数 calories。calorie-controlled diet。与 energy 在营养学中常互换使用。",
 ["卡路里", "热量"],
 "calorie intake（卡路里摄入）, low-calorie（低热量的）, empty calories（空热量）",
 "Public health advice recommends reducing daily calorie intake.", "公共卫生建议主张降低每日卡路里摄入。",
 "calor（热）+ -ie → 热量单位",
 ["energy"], [], "卡路里", "健康"),
("expand", "/ɪkˈspænd/", "v.",
 "v. ①扩大，扩展（expand into / on）；②膨胀。expansion（扩张）；expansive。expand on（详述）。反义 contract / shrink。",
 ["扩大", "扩展", "膨胀"],
 "expand into（扩展到）, expand on（详述）, economic expansion（经济扩张）",
 "The university plans to expand its online courses over the next five years.", "该大学计划在未来五年扩大在线课程。",
 "ex-（向外）+ pand（展开）→ 向外展开",
 ["extend", "grow"], ["shrink"], "扩大", "教育"),
("fashion", "/ˈfæʃn/", "n.",
 "n. ①时装，时尚（fashion industry）；②方式（in a … fashion）；③流行。v. 制作，塑造。fashionable；out of fashion。after a fashion（勉强地）。",
 ["时尚", "时装", "方式"],
 "fashion industry（时装业）, in a timely fashion（及时地）, out of fashion（过时）",
 "The fashion industry has been criticised for encouraging waste.", "时装业因助长浪费而受到批评。",
 "fac（做）同源 → 做成的样式 → 时尚/方式",
 ["style", "trend"], [], "时尚", "社会"),
("figure", "/ˈfɪɡə(r)/ · /ˈfɪɡjər/", "n. / v.",
 "n. ①数字（official figures）；②人物；③体形；④图形。v. ①认为（figure that）；②计算；③出现（figure in）。figure out（弄明白）。",
 ["数字", "人物", "体形"],
 "official figures（官方数字）, public figure（公众人物）, figure out（弄明白）",
 "Official figures show a decline in smoking among young adults.", "官方数字显示，年轻成年人中的吸烟率有所下降。",
 "原义‘形状’，引申为数字、人物轮廓",
 ["number", "shape"], [], "数字", "学术"),
("muscle", "/ˈmʌsl/", "n.",
 "n. ①肌肉（muscle strength / pain）；②实力，力量（political muscle）。muscular（肌肉的）。pull a muscle（拉伤肌肉）。",
 ["肌肉", "实力", "力量"],
 "muscle strength（肌肉力量）, pull a muscle（拉伤肌肉）, political muscle（政治实力）",
 "Regular exercise increases muscle strength and improves sleep.", "规律锻炼能增强肌肉力量并改善睡眠。",
 "拉丁语 musculus（小老鼠）→ 肌肉滚动如鼠",
 ["strength"], [], "肌肉", "健康"),
("network", "/ˈnetwɜːk/ · /ˈnetwɜːrk/", "n. / v.",
 "n. ①网络（a network of）；②人际关系网；③广播网。v. 建立联系（network with）。social network；networking。",
 ["网络", "关系网", "联网"],
 "social network（社交网络）, a network of（…的网络）, network with（与…建立联系）",
 "Professional networks can improve graduates' access to internships.", "职业关系网可以改善毕业生获得实习的机会。",
 "net（网）+ work → 网状系统",
 ["system", "web"], [], "网络", "就业"),
("positive", "/ˈpɒzətɪv/ · /ˈpɑːzətɪv/", "adj.",
 "adj. ①积极的，正面的（a positive attitude / effect）；②肯定的；③阳性的。n. 正面，优点。positively。反义 negative。",
 ["积极的", "正面的", "肯定的"],
 "a positive effect（正面影响）, positive attitude（积极态度）, test positive（检测呈阳性）",
 "The training programme had a positive effect on student confidence.", "该培训项目对学生自信心产生了积极影响。",
 "posit（放置）+ -ive → 明确给出的 → 肯定的/积极的",
 ["optimistic"], ["negative"], "积极的", "教育"),
("range", "/reɪndʒ/", "n. / v.",
 "n. ①范围（a range of；age range）；②一系列；③山脉。v. ①变动（range from A to B）；②涉及。within range。wide-ranging。",
 ["范围", "一系列", "变动"],
 "a range of（一系列）, range from A to B（从A到B不等）, age range（年龄范围）",
 "The survey covered a wide range of academic subjects.", "该调查涵盖了广泛的学科范围。",
 "原义‘排成一行’→ 从一端到另一端的跨度",
 ["scope", "variety"], [], "范围", "学术"),
("suppose", "/səˈpəʊz/ · /səˈpoʊz/", "v.",
 "v. ①认为，料想（I suppose that）；②假定（suppose / supposing that）。be supposed to（应该，被期望）。supposedly。assumption 勿混。",
 ["认为", "假定", "应该"],
 "be supposed to（应该）, suppose that（假定…）, I suppose（我想）",
 "Students are supposed to submit the assignment by Friday.", "学生应在星期五之前提交作业。",
 "sup-（在下）+ pose（放置）→ 放在前提之下 → 假定",
 ["assume"], [], "认为", "校园"),
("approach", "/əˈprəʊtʃ/ · /əˈproʊtʃ/", "n. / v.",
 "n. ①方法，途径（an approach to doing/sth）；②接近。v. ①接近；②着手处理。approachable。与 method 近义，approach 更强调视角。",
 ["方法", "接近", "处理"],
 "an approach to（…的方法）, approach a problem（着手处理问题）, as sb approaches（当某人接近时）",
 "A problem-based approach to teaching can improve critical thinking.", "基于问题的教学方法可以提高批判性思维。",
 "ap-（向）+ proach（近）→ 走近 → 方法/接近",
 ["method", "come near"], [], "方法", "教育"),
("campus", "/ˈkæmpəs/", "n.",
 "n. 校园（on campus；university campus）。off campus（校外）。campus life。复数 campuses。",
 ["校园", "大学校园"],
 "on campus（在校园内）, off campus（在校外）, campus life（校园生活）",
 "New sports facilities will be built on campus next year.", "明年将在校园内新建体育设施。",
 "拉丁语 campus（平地、场地）→ 大学场地",
 ["university grounds"], [], "校园", "校园"),
("describe", "/dɪˈskraɪb/", "v.",
 "v. 描述，描写（describe sb/sth as；describe how）。description（描述）；descriptive。beyond description。",
 ["描述", "描写", "形容"],
 "describe as（把…描述为）, a detailed description（详细描述）, describe how（描述如何）",
 "Participants were asked to describe how they prepared for examinations.", "参与者被要求描述他们如何准备考试。",
 "de-（向下）+ scribe（写）→ 写下来 → 描述",
 ["portray"], [], "描述", "学术"),
("event", "/ɪˈvent/", "n.",
 "n. ①事件（a historical event）；②活动，赛事（a sporting event）；③结果（in the event of 如果发生）。eventual（最终的）；eventually。",
 ["事件", "活动", "赛事"],
 "in the event of（如果发生）, sporting event（体育赛事）, a major event（重大事件）",
 "The conference is the most important academic event of the year.", "该会议是本年度最重要的学术活动。",
 "e-（出）+ vent（来）→ 发生出来的事",
 ["incident", "occasion"], [], "事件", "学术"),
("climate", "/ˈklaɪmət/", "n.",
 "n. ①气候（climate change）；②风气，氛围（a climate of fear / economic climate）。climatic。与 weather（天气，短时）区分。",
 ["气候", "风气", "氛围"],
 "climate change（气候变化）, economic climate（经济气候）, a climate of（…的氛围）",
 "Climate change poses a serious challenge to food production.", "气候变化对粮食生产构成严峻挑战。",
 "clima（倾斜/地带）→ 地带的长期天气 → 气候",
 ["weather"], [], "气候", "环境"),
("finally", "/ˈfaɪnəli/", "adv.",
 "adv. ①最后，终于（finally, …；it finally became clear that）；②最终。final（最后的；决赛）。at last 更口语、带感情色彩。",
 ["最后", "终于", "最终"],
 "finally decide（最终决定）, the final report（最终报告）, at the final stage（在最后阶段）",
 "The committee finally approved the new assessment policy.", "委员会最终批准了新的评估政策。",
 "final（最后的）+ -ly",
 ["eventually", "lastly"], ["initially"], "最后", "学术"),
("plastic", "/ˈplæstɪk/", "n. / adj.",
 "n. 塑料（plastic waste；不可数总称，也可说 plastics）。adj. ①塑料的；②可塑的。plastic bag / pollution。plasticity（可塑性）。",
 ["塑料", "塑料的", "可塑的"],
 "plastic waste（塑料垃圾）, plastic bag（塑料袋）, plastic pollution（塑料污染）",
 "Many cities have restricted the use of single-use plastic bags.", "许多城市已限制一次性塑料袋的使用。",
 "plast（塑造）+ -ic → 可塑造的材料",
 [], [], "塑料", "环境"),
("creative", "/kriˈeɪtɪv/", "adj.",
 "adj. 有创造力的，创造性的（creative thinking / writing）。creativity（创造力）；create；creation。creative industries（创意产业）。",
 ["有创造力的", "创造性的"],
 "creative thinking（创造性思维）, creative writing（创意写作）, creative industries（创意产业）",
 "The course aims to develop students' creative thinking skills.", "该课程旨在培养学生的创造性思维能力。",
 "create（创造）+ -ive → 能创造的",
 ["inventive"], ["unimaginative"], "有创造力的", "教育"),
("extra", "/ˈekstrə/", "adj. / adv. / n.",
 "adj. 额外的（extra time / cost）。adv. 额外地。n. 额外的事物（the extras）。extra-curricular（课外的）。",
 ["额外的", "外加的", "额外"],
 "extra time（额外时间）, extra cost（额外费用）, extra-curricular activities（课外活动）",
 "Students may need extra time to complete laboratory reports.", "学生可能需要额外时间来完成实验报告。",
 "extra-（在外）→ 在规定之外的",
 ["additional"], [], "额外的", "校园"),
("poverty", "/ˈpɒvəti/ · /ˈpɑːvərti/", "n.",
 "n. 贫穷，贫困（live in poverty；poverty line）。poor（贫穷的）；impoverished。anti-poverty policy。反义 wealth。",
 ["贫穷", "贫困"],
 "in poverty（处于贫困中）, poverty line（贫困线）, reduce poverty（减少贫困）",
 "Education is often seen as an effective way to reduce poverty.", "教育常被视为减少贫困的有效途径。",
 "poor（穷）的名词形式，-ty 表状态",
 ["need"], ["wealth"], "贫困", "社会"),
("release", "/rɪˈliːs/", "v. / n.",
 "v. ①释放，放走；②发布（release a report）；③发行。n. 释放，发布。press release（新闻稿）。release from。",
 ["释放", "发布", "发行"],
 "release a report（发布报告）, press release（新闻稿）, release from（从…中解脱）",
 "The government released a report on air quality last month.", "政府上个月发布了一份关于空气质量的报告。",
 "re-（回）+ lease（松开）→ 放开",
 ["publish", "free"], ["hold"], "发布", "社会"),
("solution", "/səˈluːʃn/", "n.",
 "n. ①解决办法（a solution to，不接 of）；②溶液。solve（解决）。find / propose a solution。solution to the problem。",
 ["解决办法", "溶液", "答案"],
 "a solution to（…的解决办法）, find a solution（找到解决办法）, chemical solution（化学溶液）",
 "There is no simple solution to the shortage of affordable housing.", "住房负担能力不足的问题没有简单的解决办法。",
 "solve（解决）+ -tion → 解决的结果",
 ["answer", "remedy"], [], "解决办法", "社会"),
("rent", "/rent/", "n. / v.",
 "n. 租金（pay rent；high rent）。v. 租用，出租（rent a flat；rent out）。rental。for rent。英式住房常用 flat，与 apartment 近义。",
 ["租金", "租用", "出租"],
 "pay rent（付租金）, rent a flat（租一套公寓）, for rent（待租）",
 "Rising rent has increased the cost of living for university students.", "不断上涨的租金提高了大学生的生活成本。",
 "原义‘付给的钱’→ 房租/租用",
 ["hire", "let"], [], "租金", "社会"),
("budget", "/ˈbʌdʒɪt/", "n. / v.",
 "n. 预算（the education budget；on a tight budget）。v. 把…编入预算。budget for。budget cut。",
 ["预算", "安排开支"],
 "on a tight budget（预算紧张）, education budget（教育预算）, budget cut（预算削减）",
 "Many students have to live on a tight budget during term time.", "许多学生在学期期间不得不精打细算。",
 "原指钱袋，引申为袋子里能花的钱 → 预算",
 ["plan"], [], "预算", "经济"),
("mission", "/ˈmɪʃn/", "n.",
 "n. ①使命，任务（a mission to do）；②代表团；③传教。mission statement（使命宣言）。the mission of the university。",
 ["使命", "任务", "代表团"],
 "a mission to（…的使命）, mission statement（使命宣言）, space mission（太空任务）",
 "The mission of the university is to widen access to higher education.", "该大学的使命是扩大高等教育的入学机会。",
 "miss（送出）+ -ion → 被派出去做的事",
 ["task", "aim"], [], "使命", "教育"),
("complain", "/kəmˈpleɪn/", "v.",
 "v. 抱怨，投诉（complain about / that / to）。complaint（投诉，抱怨）。complain of（诉说病痛）。make a complaint。",
 ["抱怨", "投诉"],
 "complain about（抱怨…）, make a complaint（提出投诉）, complain that（抱怨说）",
 "Several residents complained about noise from the construction site.", "几位居民投诉建筑工地的噪音。",
 "com-（加强）+ plain（悲叹）→ 诉苦 → 抱怨",
 ["protest"], ["praise"], "抱怨", "社会"),
("display", "/dɪˈspleɪ/", "v. / n.",
 "v. ①展示，陈列；②显示，显露。n. 展示，陈列（on display）。a display of。display screen。",
 ["展示", "陈列", "显示"],
 "on display（在展出）, display a skill（展示技能）, a public display（公开展示）",
 "The museum has a new display of scientific instruments.", "博物馆新设了科学仪器展。",
 "dis-（分开）+ play（折叠）→ 展开给人看",
 ["show", "exhibit"], ["hide"], "展示", "学术"),
("educate", "/ˈedʒukeɪt/", "v.",
 "v. 教育，培养（educate sb about / to do）。education；educated；educational；educator。well educated。",
 ["教育", "培养", "教导"],
 "educate sb about（使某人了解）, higher education（高等教育）, an educated guess（有根据的猜测）",
 "Public campaigns aim to educate young people about healthy eating.", "公益宣传旨在让年轻人了解健康饮食。",
 "e-（出）+ duc（引导）→ 引导出来 → 教育",
 ["teach", "train"], [], "教育", "教育"),
("image", "/ˈɪmɪdʒ/", "n.",
 "n. ①形象（public image）；②影像，图像；③印象。v. 构想。imaging（成像）。image of。body image。",
 ["形象", "图像", "印象"],
 "public image（公众形象）, body image（身体意象）, digital image（数字图像）",
 "Universities pay increasing attention to their public image.", "大学越来越重视自身的公众形象。",
 "imit（模仿）同源 → 摹拟出来的样子",
 ["picture", "impression"], [], "形象", "社会"),
("occur", "/əˈkɜː(r)/ · /əˈkɜːr/", "v.",
 "v. ①发生（an accident occurred；较 happen 正式）；②出现；③被想起（occur to sb）。occurrence（发生的事）。it occurred to me that…。",
 ["发生", "出现", "想起"],
 "occur to sb（某人想到）, it occurred to me that（我突然想到）, a rare occurrence（罕见之事）",
 "Similar errors occur when students translate too literally.", "学生过于直译时，类似错误就会出现。",
 "oc-（向）+ cur（跑）→ 跑到眼前 → 发生/出现",
 ["happen", "take place"], [], "发生", "学术"),
("species", "/ˈspiːʃiːz/", "n.",
 "n. 物种（单复数同形：one species, two species）。endangered species。species of。与 specie（硬币，罕用）勿混。",
 ["物种", "种"],
 "endangered species（濒危物种）, a species of（一种…）, species diversity（物种多样性）",
 "Climate change threatens many endangered species.", "气候变化威胁着许多濒危物种。",
 "spec（看/类）→ 被归为一类的生物",
 ["kind"], [], "物种", "环境"),
("performance", "/pəˈfɔːməns/ · /pərˈfɔːrməns/", "n.",
 "n. ①表现，业绩（academic / job performance）；②演出，表演；③性能。perform；performer。high-performance。",
 ["表现", "演出", "性能"],
 "academic performance（学业表现）, job performance（工作表现）, a live performance（现场演出）",
 "Sleep quality is closely related to academic performance.", "睡眠质量与学业表现密切相关。",
 "perform（履行/表演）+ -ance → 履行的结果",
 ["achievement"], [], "表现", "教育"),
("quit", "/kwɪt/", "v.",
 "v. ①停止，戒掉（quit doing / smoking）；②离开，辞职（quit a job）。quitter（轻易放弃的人）。过去式 quit 或 quitted。较正式可用 give up / resign。",
 ["停止", "辞职", "戒掉"],
 "quit smoking（戒烟）, quit a job（辞职）, quit doing（停止做）",
 "A number of teachers quit the profession because of heavy workloads.", "一些教师因工作负担过重而离开了这一职业。",
 "原义‘解除义务’→ 放下不干",
 ["stop", "resign"], ["continue"], "辞职", "就业"),
("rare", "/reə(r)/ · /rer/", "adj.",
 "adj. ①稀有的，罕见的（rare species / disease）；②半熟的（牛排）。rarely（很少）。rarity。反义 common。",
 ["稀有的", "罕见的", "半熟的"],
 "rare species（稀有物种）, a rare opportunity（难得的机会）, rarely（很少）",
 "It is rare for first-year students to publish in academic journals.", "一年级学生在学术期刊上发表文章是罕见的。",
 "与 raw 有历史联系，后固定为‘稀少’",
 ["uncommon"], ["common"], "罕见的", "学术"),
("official", "/əˈfɪʃl/", "adj. / n.",
 "adj. 官方的，正式的（official figures / language）。n. 官员。officially；office；officer（军官/警官，勿简单等同）。unofficial。",
 ["官方的", "正式的", "官员"],
 "official figures（官方数字）, official language（官方语言）, government officials（政府官员）",
 "Official figures suggest that unemployment has fallen slightly.", "官方数字显示失业率略有下降。",
 "office（公职）+ -ial → 与公职有关的",
 ["formal"], ["unofficial"], "官方的", "社会"),
("regulation", "/ˌreɡjuˈleɪʃn/", "n.",
 "n. ①规章，条例（safety regulations，常用复数）；②管理，调控。regulate（管制）；regulatory。in accordance with regulations。",
 ["规章", "条例", "调控"],
 "safety regulations（安全条例）, government regulation（政府监管）, regulate the market（调控市场）",
 "New safety regulations will apply to all campus laboratories.", "新的安全条例将适用于所有校园实验室。",
 "reg（统治）+ -ulation → 规定如何运行",
 ["rule"], [], "规章", "社会"),
("site", "/saɪt/", "n.",
 "n. ①地点，场所（a construction / heritage site）；②网站（website）。on site（在现场）。site of。与 sight（视力/景象）、cite（引用）发音或拼写易混。",
 ["地点", "场所", "网站"],
 "construction site（建筑工地）, on site（在现场）, heritage site（遗产地）",
 "The new library will be built on the site of the old sports hall.", "新图书馆将建在旧体育馆的原址上。",
 "sit（坐落）同源 → 所在之处",
 ["location", "place"], [], "地点", "社会"),
("beyond", "/bɪˈjɒnd/ · /bɪˈjɑːnd/", "prep. / adv.",
 "prep. ①超出，越过（beyond control / doubt）；②在…的那一边。adv. 在更远处。beyond one's means。the back of beyond（偏远之地）。",
 ["超出", "越过", "在…之外"],
 "beyond control（无法控制）, beyond doubt（毫无疑问）, go beyond（超越）",
 "The cost of housing is now beyond the means of many young graduates.", "住房成本现已超出许多年轻毕业生的负担能力。",
 "be- + yond（那边）→ 在更远处/超出范围",
 ["past"], ["within"], "超出", "社会"),
("connect", "/kəˈnekt/", "v.",
 "v. ①连接（connect A to/with B）；②联系。connection（联系；连接）；connected。be connected with。internet connection。",
 ["连接", "联系"],
 "connect to（连接到）, be connected with（与…有关）, internet connection（网络连接）",
 "The railway will connect the airport with the city centre.", "这条铁路将把机场与市中心连接起来。",
 "con-（共同）+ nect（绑）→ 绑在一起",
 ["link", "join"], ["disconnect"], "连接", "交通"),
("expense", "/ɪkˈspens/", "n.",
 "n. ①费用，开支（living expenses，常用复数）；②代价（at the expense of 以…为代价）。expensive（昂贵的）。expense account。",
 ["费用", "开支", "代价"],
 "living expenses（生活费）, at the expense of（以…为代价）, travel expenses（差旅费）",
 "Higher tuition fees have increased students' living expenses.", "更高的学费增加了学生的生活开支。",
 "ex-（出）+ pens（称量付钱）→ 花出去的钱",
 ["cost"], [], "费用", "经济"),
("nature", "/ˈneɪtʃə(r)/ · /ˈneɪtʃər/", "n.",
 "n. ①自然，自然界（protect nature）；②本性，性质（human nature；the nature of）。natural；naturally。by nature。in nature。",
 ["自然", "本性", "性质"],
 "human nature（人性）, the nature of（…的性质）, by nature（生性）",
 "The nature of academic work has changed with digital technology.", "学术工作的性质已随数字技术而改变。",
 "nat（出生）+ -ure → 天生的状态/万物",
 ["character"], [], "自然", "学术"),
("negative", "/ˈneɡətɪv/", "adj. / n.",
 "adj. ①消极的，负面的（a negative effect / attitude）；②否定的；③阴性的。n. 负面，否定。negatively。反义 positive。",
 ["消极的", "负面的", "否定的"],
 "a negative effect（负面影响）, negative attitude（消极态度）, test negative（检测呈阴性）",
 "Lack of sleep can have a negative effect on concentration.", "睡眠不足会对注意力产生负面影响。",
 "neg（否定）+ -ative → 否定的/负面的",
 ["adverse"], ["positive"], "负面的", "健康"),
("object", "/ˈɒbdʒɪkt/ · /ˈɑːbdʒɪkt/", "n. / v.",
 "n. ①物体，物品；②对象；③宾语（名词重音在前）。v. 反对（object to doing/sth，动词常读 /əbˈdʒekt/）。objection；objective（目标；客观的）。",
 ["物体", "对象", "反对"],
 "object to（反对）, the object of（…的对象）, an object of study（研究对象）",
 "Several teachers objected to the proposed changes in assessment.", "几位教师反对拟议中的评估改革。",
 "ob-（向）+ ject（投）→ 投到面前的东西；作动词则‘对着扔’→ 反对",
 ["thing", "oppose"], [], "物体", "学术"),
("perform", "/pəˈfɔːm/ · /pərˈfɔːrm/", "v.",
 "v. ①履行，执行（perform a task / duty）；②表演；③表现（perform well）。performance；performer。perform an experiment。",
 ["履行", "表演", "表现"],
 "perform a task（执行任务）, perform well（表现良好）, perform an experiment（做实验）",
 "The new software performed well in the laboratory tests.", "新软件在实验室测试中表现良好。",
 "per-（完全）+ form（形式）→ 把形式做出来 → 履行/表演",
 ["carry out", "act"], [], "履行", "学术"),
("recession", "/rɪˈseʃn/", "n.",
 "n. 经济衰退（economic recession；in recession）。recessive 勿简单等同。recede（后退）。a deep recession。",
 ["衰退", "经济衰退"],
 "economic recession（经济衰退）, in recession（处于衰退中）, a deep recession（严重衰退）",
 "Youth unemployment often rises during a recession.", "经济衰退期间，青年失业率往往会上升。",
 "re-（回）+ cess（走）→ 往回走 → 衰退",
 ["downturn"], ["boom"], "衰退", "经济"),
("score", "/skɔː(r)/ · /skɔːr/", "n. / v.",
 "n. ①得分，分数（test scores）；②二十（a score of，较旧）。v. 得分，评分。score well in。on that score（在那一点上）。",
 ["分数", "得分", "评分"],
 "test scores（考试分数）, score well（得分高）, a high score（高分）",
 "Students who slept longer tended to score higher in the test.", "睡眠时间更长的学生往往在测试中得分更高。",
 "原义‘刻痕计数’→ 分数",
 ["mark", "point"], [], "分数", "校园"),
("agency", "/ˈeɪdʒənsi/", "n.",
 "n. ①机构，代理机构（a government / travel agency）；②作用，能动性（human agency，学术义）。agent（代理人）。news agency。",
 ["机构", "代理", "作用"],
 "government agency（政府机构）, travel agency（旅行社）, news agency（通讯社）",
 "A government agency published new guidelines on food safety.", "一家政府机构发布了食品安全新指南。",
 "ag（做）+ -ency → 办事的机构/能力",
 ["organisation"], [], "机构", "社会"),
("apartment", "/əˈpɑːtmənt/ · /əˈpɑːrtmənt/", "n.",
 "n. 公寓套房（share an apartment）。英式日常多用 flat，美式及正式文本常用 apartment。apartment building。",
 ["公寓", "套房"],
 "share an apartment（合租公寓）, apartment building（公寓楼）, a rented apartment（租来的公寓）",
 "Many first-year students share an apartment near the campus.", "许多一年级学生在校园附近合租公寓。",
 "a-（分开）+ part（部分）→ 分成一套套的住房",
 ["flat"], ["house"], "公寓", "社会"),
("assignment", "/əˈsaɪnmənt/", "n.",
 "n. ①作业，任务（a written assignment）；②分配，指派。assign（布置，指派）。hand in an assignment。assignment to。",
 ["作业", "任务", "分配"],
 "written assignment（书面作业）, hand in an assignment（交作业）, assign a task（布置任务）",
 "Students were given two weeks to complete the written assignment.", "学生有两周时间完成这份书面作业。",
 "assign（指定）+ -ment → 指定给某人的任务",
 ["task", "homework"], [], "作业", "校园"),
("boost", "/buːst/", "v. / n.",
 "v. 促进，提高，推动（boost confidence / growth）。n. 推动，提高。a boost to。give a boost。语气积极。",
 ["促进", "提高", "推动"],
 "boost confidence（增强信心）, boost growth（推动增长）, a boost to（对…的推动）",
 "The scholarship is expected to boost applications from rural students.", "该奖学金有望增加农村学生的申请人数。",
 "原义‘从后面推一把’→ 推动提高",
 ["increase", "promote"], ["reduce"], "促进", "教育"),
("boring", "/ˈbɔːrɪŋ/", "adj.",
 "adj. 乏味的，无聊的（a boring lecture；指事物）。bored（感到无聊，指人）；bore（使厌烦）。反义 interesting。",
 ["乏味的", "无聊的"],
 "a boring lecture（乏味的讲座）, get bored（感到无聊）, bore sb（使某人厌烦）",
 "Students described the online lectures as repetitive and boring.", "学生认为这些在线讲座重复且乏味。",
 "bore（钻孔/使人烦）+ -ing → 令人厌烦的",
 ["dull"], ["interesting"], "乏味的", "校园"),
("conduct", "/kənˈdʌkt/", "v. / n.",
 "v. ①进行，实施（conduct a survey / research，动词重音在后）；②指挥；③传导。n. 行为，品行（名词常读 /ˈkɒndʌkt/）。code of conduct。",
 ["进行", "实施", "行为"],
 "conduct a survey（进行调查）, conduct research（开展研究）, code of conduct（行为准则）",
 "The team conducted a survey of more than one thousand graduates.", "该团队对一千多名毕业生进行了调查。",
 "con-（共同）+ duct（引导）→ 引导进行 → 实施/品行",
 ["carry out", "behaviour"], [], "进行", "学术"),
("consume", "/kənˈsjuːm/ · /kənˈsuːm/", "v.",
 "v. ①消耗，消费（consume energy / time）；②吃，喝。consumer；consumption。time-consuming。be consumed with（充满某种情感）。",
 ["消耗", "消费", "吃掉"],
 "consume energy（消耗能源）, energy consumption（能源消耗）, time-consuming（耗时的）",
 "Private cars consume a large share of urban energy.", "私家车消耗了城市能源的很大一部分。",
 "con-（加强）+ sume（取）→ 取尽 → 消耗",
 ["use up"], ["produce"], "消耗", "环境"),
("craft", "/krɑːft/ · /kræft/", "n. / v.",
 "n. ①手艺，工艺（arts and crafts）；②飞船，船只（spacecraft）。v. 精心制作。craftsman；craftsmanship。a well-crafted argument。",
 ["手艺", "工艺", "精心制作"],
 "arts and crafts（工艺美术）, craft a policy（精心制定政策）, spacecraft（航天器）",
 "The authors crafted a clear argument based on recent evidence.", "作者根据近期证据精心构建了一个清晰的论点。",
 "原义‘力气/技能’→ 手艺；也指船",
 ["skill", "make"], [], "手艺", "学术"),
("following", "/ˈfɒləʊɪŋ/ · /ˈfɑːloʊɪŋ/", "adj. / n. / prep.",
 "adj. 接着的，下列的（the following day / reasons）。n. 追随者；下列所述。prep. 在…之后。follow。as follows（如下）。",
 ["下列的", "接着的", "在…之后"],
 "the following day（第二天）, the following reasons（下列原因）, as follows（如下）",
 "The following reasons were given for the decline in applications.", "申请人数下降被给出了下列原因。",
 "follow（跟随）+ -ing → 跟在后面的",
 ["next", "subsequent"], ["previous"], "下列的", "学术"),
("immigrant", "/ˈɪmɪɡrənt/", "n. / adj.",
 "n. 移民（入境者）。adj. 移民的。immigrate（移入）；emigrant（出境移民）；immigration。immigrant workers。",
 ["移民", "入境移民"],
 "immigrant workers（移民工人）, immigration policy（移民政策）, recent immigrants（新近移民）",
 "The study examined the educational experiences of immigrant students.", "该研究考察了移民学生的教育经历。",
 "im-（入）+ migr（迁移）→ 迁入者",
 [], ["emigrant"], "移民", "社会"),
("instance", "/ˈɪnstəns/", "n.",
 "n. 例子，实例（for instance = for example；an instance of）。in this instance（在这种情况下）。instance 较 example 略正式。",
 ["例子", "实例", "情况"],
 "for instance（例如）, an instance of（…的实例）, in this instance（在这种情况下）",
 "Some courses, for instance statistics, require additional laboratory work.", "有些课程，例如统计学，需要额外的实验工作。",
 "in-（向）+ stance（站）→ 摆出来给人看的例子",
 ["example"], [], "例如", "学术"),
("partner", "/ˈpɑːtnə(r)/ · /ˈpɑːrtnər/", "n.",
 "n. ①伙伴，合伙人（a business / research partner）；②配偶，伴侣。v. 做伙伴。partnership。partner with。",
 ["伙伴", "合伙人", "伴侣"],
 "research partner（研究伙伴）, business partner（商业伙伴）, partnership（伙伴关系）",
 "The university signed an agreement with an industry partner.", "该大学与一家产业合作伙伴签署了协议。",
 "part（部分）+ -ner → 共同分担的人",
 ["colleague", "associate"], [], "伙伴", "就业"),
("private", "/ˈpraɪvət/", "adj.",
 "adj. ①私人的（private life / information）；②私立的（private school）；③私下的。in private。privacy（隐私）。反义 public。",
 ["私人的", "私立的", "私下的"],
 "private school（私立学校）, in private（私下）, private information（私人信息）",
 "Private schools often charge higher fees than state schools.", "私立学校的收费往往高于公立学校。",
 "priv（个人的）+ -ate → 属于个人的",
 ["personal"], ["public"], "私人的", "教育"),
("publish", "/ˈpʌblɪʃ/", "v.",
 "v. ①出版，发表（publish a paper / book）；②公布。publication；publisher；published。publish findings。",
 ["出版", "发表", "公布"],
 "publish a paper（发表论文）, published research（已发表的研究）, publication（出版物；发表）",
 "The findings will be published in an international journal.", "这些发现将发表在一份国际期刊上。",
 "public（公开的）+ -ish → 使公开 → 出版/发表",
 ["issue", "print"], [], "发表", "学术"),
("significant", "/sɪɡˈnɪfɪkənt/", "adj.",
 "adj. ①重要的，显著的（a significant difference / increase）；②有意义的。significantly；significance。statistically significant（统计学显著）。",
 ["重要的", "显著的", "有意义的"],
 "a significant increase（显著增加）, significant difference（显著差异）, social significance（社会意义）",
 "There was a significant increase in applications after fees were reduced.", "学费降低后，申请人数显著增加。",
 "sign（标记）+ -ificant → 带有重要标记的",
 ["important", "notable"], ["insignificant"], "显著的", "学术"),
("strategy", "/ˈstrætədʒi/", "n.",
 "n. 战略，策略（a strategy for / to do）。strategic（战略的）；strategically。learning strategy。long-term strategy。",
 ["策略", "战略"],
 "learning strategy（学习策略）, a strategy for（…的策略）, long-term strategy（长期战略）",
 "The government announced a long-term strategy to cut carbon emissions.", "政府宣布了一项削减碳排放的长期战略。",
 "原指将军之术 → 全局性办法",
 ["plan", "tactic"], [], "策略", "社会"),
("understanding", "/ˌʌndəˈstændɪŋ/ · /ˌʌndərˈstændɪŋ/", "n. / adj.",
 "n. ①理解，了解（an understanding of）；②谅解。adj. 体谅的。understand；misunderstanding。come to an understanding。",
 ["理解", "了解", "谅解"],
 "an understanding of（对…的理解）, mutual understanding（相互理解）, come to an understanding（达成谅解）",
 "The course develops a deeper understanding of climate policy.", "该课程加深对气候政策的理解。",
 "understand（理解）+ -ing → 理解的状态",
 ["comprehension"], ["misunderstanding"], "理解", "教育"),
("appeal", "/əˈpiːl/", "n. / v.",
 "n. ①吸引力（popular appeal）；②呼吁；③上诉。v. ①呼吁（appeal to sb to do / for）；②吸引（appeal to）；③上诉。appealing。",
 ["呼吁", "吸引", "上诉"],
 "appeal to（吸引；向…呼吁）, an appeal for（为…发出的呼吁）, popular appeal（大众吸引力）",
 "The charity appealed to the public for donations after the flood.", "洪水过后，该慈善机构呼吁公众捐款。",
 "ap-（向）+ peal（推）→ 推向某人 → 呼吁/吸引",
 ["attract", "call"], [], "呼吁", "社会"),
("application", "/ˌæplɪˈkeɪʃn/", "n.",
 "n. ①申请（job / university application）；②应用（the application of theory）；③应用程序。apply；applicant。application form。",
 ["申请", "应用", "应用程序"],
 "job application（求职申请）, application form（申请表）, the application of（…的应用）",
 "Online application forms have reduced the time needed to apply.", "在线申请表缩短了申请所需的时间。",
 "apply（申请/应用）+ -ation",
 ["request", "use"], [], "申请", "就业"),
("being", "/ˈbiːɪŋ/", "n.",
 "n. ①生物，人（a human being）；②存在（the meaning of being）。come into being（形成，产生）。well-being（幸福，安康）。",
 ["生物", "人", "存在"],
 "human being（人）, come into being（形成）, well-being（安康）",
 "The committee came into being after the 2018 education reform.", "该委员会是在 2018 年教育改革之后成立的。",
 "be（是/存在）+ -ing → 存在之物",
 ["creature"], [], "人", "学术"),
("carrot", "/ˈkærət/", "n.",
 "n. ①胡萝卜；②（比喻）好处，利诱（carrot and stick 软硬兼施）。carrot juice。复数 carrots。",
 ["胡萝卜", "利诱", "好处"],
 "carrot and stick（软硬兼施）, a carrot for（给…的好处）, carrot juice（胡萝卜汁）",
 "The new tax cut is seen as a carrot to encourage investment.", "新的减税被视为鼓励投资的一种利诱。",
 "本义蔬菜；政策语境中常作‘奖励手段’",
 ["incentive"], ["stick"], "胡萝卜", "经济"),
("claim", "/kleɪm/", "v. / n.",
 "n. / v. ①声称（claim that / to be）；②索要，索赔（claim compensation）；③主张。make a claim。claimant。学术写作中 claim 需证据支持。",
 ["声称", "索要", "主张"],
 "claim that（声称…）, make a claim（提出主张/索赔）, claim compensation（索赔）",
 "The authors claim that shorter lectures improve attention.", "作者声称，更短的讲座能提高注意力。",
 "clam（呼喊）同源 → 大声提出要求/说法",
 ["assert", "demand"], [], "声称", "学术"),
("colleague", "/ˈkɒliːɡ/ · /ˈkɑːliːɡ/", "n.",
 "n. 同事，同僚（a colleague at work）。collegial（同事间协作的）。比 workmate 正式。复数 colleagues。",
 ["同事", "同僚"],
 "a colleague at work（工作中的同事）, former colleague（以前的同事）, academic colleagues（学术同行）",
 "She discussed the findings with colleagues in the same department.", "她与同一系的同事讨论了这些发现。",
 "col-（共同）+ league（联盟）→ 同一团体中的人",
 ["co-worker"], [], "同事", "就业"),
("determine", "/dɪˈtɜːmɪn/ · /dɪˈtɜːrmɪn/", "v.",
 "v. ①决定，确定（determine the cause / that）；②下决心（determine to do）。determination（决心）；determined。be determined by。",
 ["决定", "确定", "下决心"],
 "determine the cause（确定原因）, be determined by（由…决定）, determination（决心）",
 "Further tests are needed to determine the cause of the decline.", "还需要进一步检测才能确定下降的原因。",
 "de-（完全）+ termin（界限）→ 划定界限 → 确定",
 ["decide", "establish"], [], "确定", "学术"),
("essential", "/ɪˈsenʃl/", "adj. / n.",
 "adj. 必不可少的，本质的（essential to/for；it is essential that）。n. 必需品（the essentials）。essentially。比 important 语气更强。",
 ["必不可少的", "本质的", "要点"],
 "essential for（对…必不可少）, it is essential that（必须…）, the essentials（要点；必需品）",
 "Digital literacy is now essential for most university courses.", "数字素养现在对大多数大学课程都必不可少。",
 "essenc（本质）+ -ial → 属于本质的",
 ["necessary", "vital"], ["optional"], "必不可少的", "教育"),
("handle", "/ˈhændl/", "v. / n.",
 "v. ①处理，应付（handle a problem / pressure）；②拿，触摸。n. 柄，把手。handler。handle with care。",
 ["处理", "应付", "把手"],
 "handle a problem（处理问题）, handle pressure（应对压力）, the handle of（…的把手）",
 "The training helps new teachers handle classroom pressure.", "该培训帮助新教师应对课堂压力。",
 "hand（手）+ -le → 用手拿/应付",
 ["deal with", "manage"], [], "处理", "就业"),
("launch", "/lɔːntʃ/", "v. / n.",
 "v. ①发动，发起（launch a campaign / product）；②发射。n. 发射，上市。the launch of。launch into。",
 ["发起", "推出", "发射"],
 "launch a campaign（发起一场运动）, launch a product（推出产品）, the launch of（…的启动/上市）",
 "The university launched a campaign to promote mental health.", "该大学发起了一场促进心理健康的运动。",
 "原指使船下水 → 使某事物开始运行",
 ["start", "introduce"], [], "发起", "社会"),
("scientific", "/ˌsaɪənˈtɪfɪk/", "adj.",
 "adj. 科学的（scientific research / evidence）。science；scientist；scientifically。scientific method。反义 unscientific。",
 ["科学的", "科学性的"],
 "scientific research（科学研究）, scientific evidence（科学证据）, scientific method（科学方法）",
 "The conclusion is based on scientific evidence from several studies.", "该结论基于多项研究提供的科学证据。",
 "science（科学）+ -ific → 属于科学的",
 ["empirical"], ["unscientific"], "科学的", "学术"),
("spot", "/spɒt/ · /spɑːt/", "n. / v.",
 "n. ①地点（a tourist spot）；②斑点；③少量。v. 发现，认出（spot a mistake）。on the spot（当场；在现场）。spotted。",
 ["地点", "发现", "斑点"],
 "on the spot（当场；在现场）, spot a mistake（发现错误）, a tourist spot（旅游地点）",
 "The inspector spotted several safety problems in the laboratory.", "检查员在实验室发现了几处安全问题。",
 "原义‘点’，引申为某一点位置或看出某点",
 ["place", "notice"], [], "发现", "学术"),
]

assert len(ROWS) == 77
WORDS = numbered(ROWS)
assert [w["word"] for w in WORDS] == [r[0] for r in ROWS]


def cet4_words():
    return [dict(w) for w in WORDS]


if __name__ == "__main__":
    from inject_cet4 import write_list
    write_list(3, cet4_words(), excel=[r[0] for r in ROWS])
