# -*- coding: utf-8 -*-
"""CET-4 List 1 cards. Excel order; gaozhong field standard."""
from gaozhong_entry import numbered

ROWS = [
("according to", "/əˈkɔːdɪŋ tə/ · /əˈkɔːrdɪŋ tə/", "prep.",
 "prep. ①按照，根据（后接名词短语，引出信息来源或依据）；②据…所说。常用 according to the report / survey。不可说 according to me，宜用 in my opinion。according as 已罕用。",
 ["根据", "按照", "据"],
 "according to the report（根据报告）, according to plan（按计划）, according to sb（据某人所说）",
 "According to the latest report, graduate employment has improved.", "根据最新报告，毕业生就业情况有所改善。",
 "accord（一致）+ -ing → 与某说法一致 → 根据",
 ["in line with"], [], "根据", "学术"),
("author", "/ˈɔːθə(r)/ · /ˈɔːθər/", "n.",
 "n. ①作者，著者（the author of a paper）；②作家；③创始人，发起者。动词 author（撰写，较正式）。派生 authorship（作者身份）、authoritative（权威的）。",
 ["作者", "作家", "著者"],
 "the author of（…的作者）, the authors argue that（作者认为）, co-author（合著者）",
 "The author of the study argues that sleep quality affects academic performance.", "该研究的作者认为，睡眠质量影响学业表现。",
 "与 authority（权威）同源：写书的人有话语权",
 ["writer"], [], "作者", "学术"),
("accord", "/əˈkɔːd/ · /əˈkɔːrd/", "n. / v.",
 "n. ①一致，符合（in accord with）；②协议，谅解。v. ①授予，给予（accord sb sth，较正式）；②与…相符。of one's own accord（自愿地）。派生 accordance（一致）。",
 ["一致", "协议", "给予"],
 "in accord with（与…一致）, of one's own accord（自愿地）, reach an accord（达成协议）",
 "The new policy is in accord with the university's long-term plan.", "新政策与学校的长期规划一致。",
 "ac-（加强）+ cord（心）→ 心心相印 → 一致",
 ["agreement", "grant"], ["conflict"], "一致", "学术"),
("likely", "/ˈlaɪkli/", "adj. / adv.",
 "adj. ①可能的（be likely to do / that）；②合适的，有希望的。adv. 可能（多与 most / very 连用：most likely）。It is likely that… 为四级高频句式。反义 unlikely。",
 ["可能的", "可能", "有希望的"],
 "be likely to（可能…）, it is likely that（很可能…）, most likely（很可能）",
 "Students who review regularly are more likely to remember key terms.", "定期复习的学生更可能记住关键术语。",
 "like（像）+ -ly → 看起来会那样 → 可能",
 ["probable"], ["unlikely"], "可能的", "学术"),
("system", "/ˈsɪstəm/", "n.",
 "n. ①系统，体系（education / transport system）；②制度；③方法，做法；④身体（the immune system）。a system of…（一套…体系）。派生 systematic（系统的）。",
 ["系统", "体系", "制度"],
 "education system（教育体系）, immune system（免疫系统）, a system of（一套…）",
 "The education system needs reform to support rural students.", "教育体系需要改革，以支持农村学生。",
 "sys-（一起）+ stem（站立）→ 各部分立在一起 → 系统",
 ["structure", "network"], [], "系统", "社会"),
("kid", "/kɪd/", "n.",
 "n. ①小孩，儿童（口语，书面可用 child）；②年轻人；③小山羊。kid sb（开玩笑）。四级阅读教育类文章常出现 kids 指儿童受试者。复数 kids。",
 ["小孩", "儿童", "孩子"],
 "college kids（大学生，口语）, kid sb（开某人玩笑）, the kids（孩子们）",
 "The experiment involved kids aged between eight and twelve.", "该实验的对象是八至十二岁的儿童。",
 "口语词，正式写作宜用 child / children",
 ["child"], ["adult"], "小孩", "教育"),
("interest", "/ˈɪntrəst/ · /ˈɪntərɪst/", "n. / v.",
 "n. ①兴趣（take / show interest in）；②利益（in the public interest）；③利息。v. 使感兴趣（interest sb in sth）。interested（感兴趣的，指人）；interesting（有趣的，指物）。",
 ["兴趣", "利益", "利息"],
 "take interest in（对…感兴趣）, in the public interest（为了公共利益）, interest rate（利率）",
 "The course is designed to raise students' interest in scientific research.", "该课程旨在提高学生对科研的兴趣。",
 "inter-（在中间）+ est（存在）→ 置身其中 → 兴趣/利益",
 ["concern", "curiosity"], [], "兴趣", "校园"),
("identify", "/aɪˈdentɪfaɪ/", "v.",
 "v. ①识别，认出（identify sb/sth as）；②确定，找出（identify the cause）；③认同（identify with）。派生 identification（身份证明；识别）、identity（身份）。",
 ["识别", "确定", "认同"],
 "identify the cause（找出原因）, identify with（认同）, identify as（认定为）",
 "Researchers need to identify the main factors behind the decline.", "研究者需要找出导致这一下降的主要因素。",
 "ident（同一）+ -ify（使）→ 认出是同一个 → 识别",
 ["recognise", "detect"], [], "识别", "学术"),
("happen", "/ˈhæpən/", "v.",
 "v. ①发生（sth happens to sb；不用被动表‘事情被发生’）；②碰巧（happen to do）。What happened? 询问经过。It so happened that…（碰巧）。近义 occur（较正式）。",
 ["发生", "碰巧"],
 "happen to sb（发生在某人身上）, happen to do（碰巧做）, what happened（发生了什么）",
 "Similar problems tend to happen when data are collected too quickly.", "数据收集过快时，类似问题往往会发生。",
 "hap（运气）→ 碰巧遇上 → 发生",
 ["occur", "take place"], [], "发生", "通用"),
("technology", "/tekˈnɒlədʒi/ · /tekˈnɑːlədʒi/", "n.",
 "n. ①技术，科技（不可数总称）；②某一技术（a new technology，可数）。information technology（信息技术）。派生 technological（技术的）、technician（技术员）。",
 ["技术", "科技"],
 "information technology（信息技术）, new technology（新技术）, technology companies（科技公司）",
 "Digital technology has changed the way students search for information.", "数字技术改变了学生检索信息的方式。",
 "techno-（技艺）+ -logy（学科）→ 技术之学",
 ["technique"], [], "技术", "科技"),
("improve", "/ɪmˈpruːv/", "v.",
 "v. ①改善，提高（improve sth / improve in）；②变得更好。improve on（改进已有事物，使之更好）。派生 improvement。反义 worsen / deteriorate。",
 ["改善", "提高", "改进"],
 "improve the quality of（提高…质量）, improve on（改进）, an improvement in（在…方面的改善）",
 "Regular feedback can improve the quality of student writing.", "定期反馈可以提高学生写作的质量。",
 "im-（使）+ prove（证明/好）→ 使更好",
 ["enhance", "better"], ["worsen"], "改善", "学术"),
("benefit", "/ˈbenɪfɪt/", "n. / v.",
 "n. ①益处，好处（the benefits of）；②福利（unemployment benefit）。v. 有益于（benefit sb）；受益（benefit from）。beneficial（有益的）。",
 ["益处", "好处", "受益"],
 "benefit from（从…中受益）, the benefits of（…的好处）, for sb's benefit（为了某人的利益）",
 "Both teachers and students can benefit from smaller class sizes.", "师生都能从较小的班级规模中受益。",
 "bene-（好）+ fit（做）→ 做好事 → 益处",
 ["advantage", "gain"], ["harm"], "益处", "社会"),
("social", "/ˈsəʊʃl/ · /ˈsoʊʃl/", "adj.",
 "adj. ①社会的（social problems / media）；②社交的（social skills）；③群居的。social media（社交媒体）为四级高频。派生 society、socially。",
 ["社会的", "社交的"],
 "social media（社交媒体）, social problem（社会问题）, social skills（社交技能）",
 "Social media use is now a major topic in communication studies.", "社交媒体使用现已成为传播学研究的一个主要课题。",
 "soci（同伴）+ -al → 与群体有关 → 社会的",
 ["public"], ["private"], "社会的", "社会"),
("provide", "/prəˈvaɪd/", "v.",
 "v. ①提供，供给（provide sb with sth / provide sth for sb）；②规定（法律条款 provide that）。provided / providing that（假如，条件状语）。派生 provider、provision。",
 ["提供", "供给", "规定"],
 "provide sb with（向某人提供）, provide for（供养；为…做准备）, provided that（假如）",
 "The library provides students with free access to academic journals.", "图书馆向学生免费提供学术期刊的使用权。",
 "pro-（提前）+ vide（看）→ 预先备好 → 提供",
 ["supply", "offer"], [], "提供", "校园"),
("require", "/rɪˈkwaɪə(r)/ · /rɪˈkwaɪər/", "v.",
 "v. ①需要（require sth / that）；②要求，规定（be required to do）。requirement（要求，必要条件）。较 demand 正式、语气弱于 demand。",
 ["需要", "要求", "规定"],
 "be required to（被要求…）, require that（要求…）, meet the requirements（满足要求）",
 "Applicants are required to submit a research proposal.", "申请者须提交一份研究计划。",
 "re-（再）+ quire（寻求）→ 再求得到 → 需要/要求",
 ["need", "demand"], [], "要求", "学术"),
("item", "/ˈaɪtəm/", "n.",
 "n. ①一件物品，项目（an item of clothing / news）；②条款，细目；③试题中的题目。news item（一则新闻）。复数 items。",
 ["项目", "条款", "一件物品"],
 "an item of（一件…）, news item（一则新闻）, questionnaire item（问卷题目）",
 "Each item on the questionnaire was tested in a pilot study.", "问卷上的每一道题目都在预调查中做过测试。",
 "原义‘同样也’，后指清单上的一项",
 ["article", "entry"], [], "项目", "学术"),
("include", "/ɪnˈkluːd/", "v.",
 "v. ①包括，包含（把某人或某物算作整体的一部分）；②算入。include sb/sth in。including（包括…在内，后接被包括部分）；included（包括在内，常后置）。反义 exclude。",
 ["包括", "包含", "算入"],
 "include sb/sth in（把…包括在内）, including（包括…在内）, tax included（含税）",
 "The survey included more than two thousand university students.", "该调查涵盖了两千多名大学生。",
 "in-（进入）+ clud（关闭）→ 关进里面 → 包括",
 ["contain", "comprise"], ["exclude"], "包括", "学术"),
("market", "/ˈmɑːkɪt/ · /ˈmɑːrkɪt/", "n. / v.",
 "n. ①市场（the labour market，英式 labour）；②集市；③需求，销路。v. 推销，营销。market economy（市场经济）；marketing（市场营销）。",
 ["市场", "营销", "推销"],
 "labour market（劳动力市场）, market economy（市场经济）, market a product（推销产品）",
 "Competition in the labour market has become more intense.", "劳动力市场上的竞争变得更加激烈。",
 "原指交易场所，后引申为供求关系",
 ["trade"], [], "市场", "经济"),
("blank", "/blæŋk/", "adj. / n.",
 "adj. ①空白的（a blank page）；②茫然的（a blank look）；③无表情的。n. 空白处（fill in the blanks）。go blank（脑子一片空白）。",
 ["空白的", "茫然的", "空白处"],
 "fill in the blanks（填空）, a blank page（空白页）, go blank（脑子一片空白）",
 "Candidates were asked to fill in the blanks with suitable words.", "考生须用恰当的词填空。",
 "与 blanc（白）同源 → 空白",
 ["empty"], ["filled"], "空白的", "校园"),
("adult", "/ˈædʌlt/ · /əˈdʌlt/", "n. / adj.",
 "n. 成年人。adj. ①成年的；②成熟的；③成人的（adult education）。adulthood（成年期）。反义 child。",
 ["成年人", "成年的", "成人的"],
 "adult education（成人教育）, young adults（年轻人）, adult population（成年人口）",
 "Adult education programmes help workers update their skills.", "成人教育项目帮助劳动者更新技能。",
 "ad-（向）+ ult（生长）→ 长成 → 成年",
 ["grown-up"], ["child"], "成年人", "社会"),
("product", "/ˈprɒdʌkt/ · /ˈprɑːdʌkt/", "n.",
 "n. ①产品，制品；②产物，结果（a product of）；③乘积（数学）。produce（v. 生产；n. 农产品，重音在前）。production（生产）；productivity（生产率）。",
 ["产品", "产物", "制品"],
 "a new product（新产品）, a product of（…的产物）, product design（产品设计）",
 "The company launched a new product after two years of research.", "该公司在两年研究之后推出了一款新产品。",
 "pro-（向前）+ duct（引导）→ 引出来的东西 → 产品",
 ["goods", "output"], [], "产品", "经济"),
("activity", "/ækˈtɪvəti/", "n.",
 "n. ①活动（classroom / economic activity）；②活跃，活跃状态。复数 activities。active（积极的，活跃的）。physical activity（体育活动）为健康类高频。",
 ["活动", "活跃"],
 "economic activity（经济活动）, physical activity（体育活动）, classroom activities（课堂活动）",
 "Physical activity is associated with better mental health.", "体育活动与更好的心理健康相关。",
 "act（做）+ -ivity → 正在做的事 → 活动",
 ["action"], [], "活动", "健康"),
("local", "/ˈləʊkl/ · /ˈloʊkl/", "adj. / n.",
 "adj. ①当地的，地方的（local government / news）；②局部的。n. 当地人（the locals）。locally（在当地）。反义 national / global。",
 ["当地的", "地方的", "当地人"],
 "local government（地方政府）, local community（当地社区）, the locals（当地人）",
 "Local governments are responsible for public transport in many cities.", "在许多城市，地方政府负责公共交通。",
 "loc（地方）+ -al → 属于某地的",
 ["regional"], ["national", "global"], "当地的", "社会"),
("comprehension", "/ˌkɒmprɪˈhenʃn/ · /ˌkɑːmprɪˈhenʃn/", "n.",
 "n. ①理解，理解力（reading comprehension）；②包含。beyond comprehension（无法理解）。动词 comprehend；形容词 comprehensive（全面的，勿与 comprehension 混淆）。",
 ["理解", "理解力", "阅读理解"],
 "reading comprehension（阅读理解）, beyond comprehension（无法理解）, listening comprehension（听力理解）",
 "Reading comprehension depends on both vocabulary and background knowledge.", "阅读理解既依赖词汇量，也依赖背景知识。",
 "com-（一起）+ prehend（抓住）→ 一把抓住意思 → 理解",
 ["understanding"], [], "理解", "校园"),
("result", "/rɪˈzʌlt/", "n. / v.",
 "n. ①结果，后果（as a result）；②成绩，比分。v. result in（导致）；result from（起因于）。as a result of（由于）。勿与 affect/effect 混淆：result 是发生后的结局。",
 ["结果", "导致", "成绩"],
 "as a result（因此）, result in（导致）, result from（由…引起）",
 "The policy resulted in a significant decline in air pollution.", "该政策导致空气污染显著下降。",
 "re-（回）+ sult（跳）→ 跳回来的东西 → 结果",
 ["outcome", "consequence"], ["cause"], "结果", "学术"),
("create", "/kriˈeɪt/", "v.",
 "v. ①创造，创建（create jobs / opportunities）；②造成，引起（create problems）。creative（有创造力的）；creation（创造）；creature（生物）。",
 ["创造", "创建", "造成"],
 "create jobs（创造就业）, create opportunities（创造机会）, create a problem（造成问题）",
 "The programme was designed to create more opportunities for young researchers.", "该项目旨在为青年研究者创造更多机会。",
 "cre（生长）+ -ate → 使生长出来 → 创造",
 ["produce", "generate"], ["destroy"], "创造", "经济"),
("support", "/səˈpɔːt/ · /səˈpɔːrt/", "v. / n.",
 "v. ①支持，拥护；②支撑；③供养；④为…提供证据（support a claim）。n. 支持，资助（financial support）。supportive（支持的）。",
 ["支持", "支撑", "供养"],
 "financial support（资金支持）, support a claim（支持某一观点）, in support of（支持）",
 "The findings support the claim that sleep affects memory.", "这些发现支持‘睡眠影响记忆’这一说法。",
 "sup-（在下）+ port（运）→ 从下面托住 → 支持",
 ["back", "assist"], ["oppose"], "支持", "学术"),
("focus", "/ˈfəʊkəs/ · /ˈfoʊkəs/", "v. / n.",
 "v. ①集中（focus on）；②调焦。n. ①焦点，重点（the focus of the study）；②关注点。复数 foci 或 focuses。stay focused（保持专注）。",
 ["集中", "焦点", "重点"],
 "focus on（集中于）, the focus of（…的重点）, stay focused（保持专注）",
 "The study focuses on the impact of online learning on writing skills.", "该研究集中探讨在线学习对写作能力的影响。",
 "原义‘炉火’，引申为光线汇聚点 → 焦点",
 ["concentrate", "centre"], [], "集中", "学术"),
("concern", "/kənˈsɜːn/ · /kənˈsɜːrn/", "n. / v.",
 "n. ①担心，忧虑（concern about / over）；②关心的事；③公司（a large concern）。v. ①涉及（concern sb/sth）；②使担心。be concerned with（与…有关）；be concerned about（担心）。",
 ["担心", "涉及", "关心"],
 "concern about（对…的担心）, be concerned with（与…有关）, as far as sb is concerned（就某人而言）",
 "There is growing concern about the mental health of university students.", "人们对大学生心理健康的担忧与日俱增。",
 "con-（共同）+ cern（分辨）→ 与己有关 → 关切",
 ["worry", "involve"], [], "担心", "社会"),
("essay", "/ˈeseɪ/", "n.",
 "n. ①短文，论说文（academic essay）；②小品文。write / submit an essay。essay question（论述题）。比 article 更偏学生习作或命题作文。",
 ["短文", "论说文", "作文"],
 "write an essay（写一篇短文）, academic essay（学术短文）, essay question（论述题）",
 "Students were asked to write an essay on the role of technology in education.", "学生须就技术在教育中的作用写一篇短文。",
 "源自古法语 essai（尝试）→ 试着论述",
 ["paper", "composition"], [], "短文", "校园"),
("career", "/kəˈrɪə(r)/ · /kəˈrɪr/", "n.",
 "n. ①职业，事业（a career in teaching）；②生涯，经历。career development / path（职业发展/路径）。勿与 job（具体工作）、occupation（职业类别）简单等同：career 强调长期发展。",
 ["职业", "事业", "生涯"],
 "career development（职业发展）, a career in（从事…职业）, career path（职业路径）",
 "Career development has become a central concern for university graduates.", "职业发展已成为大学毕业生的核心关切。",
 "原义‘跑道’，引申为人生跑道 → 事业",
 ["profession"], [], "职业", "就业"),
("project", "/ˈprɒdʒekt/ · /ˈprɑːdʒekt/", "n. / v.",
 "n. ①项目，课题（research project；名词重音在前）；②方案。v. ①规划，预计（project that）；②投射，放映（动词常读 /prəˈdʒekt/）。project onto（投射到）。",
 ["项目", "课题", "预计"],
 "research project（研究项目）, project that（预计…）, project onto（投射到）",
 "The research project will last for three years.", "该研究项目将持续三年。",
 "pro-（向前）+ ject（投）→ 向前投出的计划 → 项目",
 ["scheme", "plan"], [], "项目", "学术"),
("design", "/dɪˈzaɪn/", "n. / v.",
 "n. ①设计；②图案；③意图（by design 故意地）。v. 设计，构思（be designed to do 旨在）。designer（设计师）；by accident 与 by design 相对。",
 ["设计", "构思", "图案"],
 "be designed to（旨在）, by design（故意地）, product design（产品设计）",
 "The course is designed to develop students' critical thinking.", "该课程旨在培养学生的批判性思维。",
 "de-（加强）+ sign（标记）→ 作出标记 → 设计",
 ["plan", "devise"], [], "设计", "学术"),
("finding", "/ˈfaɪndɪŋ/", "n.",
 "n. ①（研究）发现，结果（research findings，常用复数）；②裁决，调查结论。The findings suggest / show that… 为论文高频句。动词 find。",
 ["发现", "研究结果", "结论"],
 "research findings（研究发现）, the findings suggest（研究结果表明）, key findings（主要发现）",
 "The findings suggest that sleep quality affects exam performance.", "研究结果表明，睡眠质量影响考试成绩。",
 "find（找到）+ -ing → 找到的东西 → 发现",
 ["result", "conclusion"], [], "发现", "学术"),
("ability", "/əˈbɪləti/", "n.",
 "n. ①能力，才能（the ability to do）；②技能。ability in / for 较少，四级多用 the ability to。派生 able、unable、enable。复数 abilities。",
 ["能力", "才能"],
 "the ability to（做…的能力）, language ability（语言能力）, cognitive ability（认知能力）",
 "The ability to work in a team is valued by most employers.", "大多数雇主看重团队协作能力。",
 "able（能够的）+ -ity → 能够的状态 → 能力",
 ["capability", "skill"], ["inability"], "能力", "就业"),
("disease", "/dɪˈziːz/", "n.",
 "n. ①疾病（heart / infectious disease）；②弊端（a disease of society，比喻）。disease 多指具体病症；illness 可指生病状态。prevent / treat a disease。",
 ["疾病", "病"],
 "heart disease（心脏病）, infectious disease（传染病）, prevent disease（预防疾病）",
 "Heart disease remains a leading cause of death worldwide.", "心脏病仍是全球主要死因之一。",
 "dis-（不）+ ease（舒适）→ 不舒适 → 疾病",
 ["illness"], ["health"], "疾病", "健康"),
("digital", "/ˈdɪdʒɪtl/", "adj.",
 "adj. ①数字的，数码的（digital technology / media）；②手指的（较少考）。digital divide（数字鸿沟）。反义 analogue（模拟的）。名词 digit（数字；手指）。",
 ["数字的", "数码的"],
 "digital technology（数字技术）, digital media（数字媒体）, digital divide（数字鸿沟）",
 "Digital media have transformed the way news is produced and shared.", "数字媒体改变了新闻的生产和传播方式。",
 "digit（手指/数字）+ -al → 用数字表示的",
 ["electronic"], ["analogue"], "数字的", "科技"),
("tend", "/tend/", "v.",
 "v. ①往往会，倾向（tend to do，四级最常用）；②照料（tend the sick / a garden）。tendency（倾向）。People tend to… 表普遍趋势，语气弱于 will always。",
 ["倾向于", "往往会", "照料"],
 "tend to do（往往会…）, tend the sick（照料病人）, have a tendency to（有…倾向）",
 "University students tend to underestimate the time required for revision.", "大学生往往会低估复习所需的时间。",
 "原义‘伸向’，引申为朝某方向发展",
 ["be inclined to"], [], "倾向于", "学术"),
("decade", "/ˈdekeɪd/", "n.",
 "n. 十年，十年期。over the past decade（在过去十年里）为阅读高频。decades of（数十年的）。词根 dec- 表‘十’（decimal 十进制的）。",
 ["十年", "十年期"],
 "over the past decade（在过去十年里）, for decades（数十年来）, a decade of（…的十年）",
 "Over the past decade, online courses have expanded rapidly.", "在过去十年里，在线课程迅速扩展。",
 "dec-（十）+ -ade → 十个一组 → 十年",
 ["ten years"], [], "十年", "学术"),
("average", "/ˈævərɪdʒ/", "n. / adj. / v.",
 "n. 平均，平均数（on average；the average of）。adj. ①平均的；②普通的（an average student）。v. 平均为。above / below average。",
 ["平均", "普通的", "平均数"],
 "on average（平均而言）, above average（高于平均水平）, the average of（…的平均数）",
 "On average, students spent two hours a day on the assignment.", "学生平均每天花两小时完成这项作业。",
 "源出海运分摊损失，后指平均数",
 ["mean"], [], "平均", "学术"),
("culture", "/ˈkʌltʃə(r)/ · /ˈkʌltʃər/", "n.",
 "n. ①文化（cultural differences）；②培养（细菌 culture；企业文化 company culture）。cultural（文化的）；multicultural（多元文化的）。",
 ["文化", "培养"],
 "cultural differences（文化差异）, company culture（企业文化）, popular culture（大众文化）",
 "Cultural differences may affect how students take part in class discussion.", "文化差异可能影响学生参与课堂讨论的方式。",
 "cult（耕种）+ -ure → 耕作/教养 → 文化",
 ["civilisation"], [], "文化", "社会"),
("opportunity", "/ˌɒpəˈtjuːnəti/ · /ˌɑːpərˈtuːnəti/", "n.",
 "n. 机会，时机（opportunity to do / for sth）。equal opportunity（平等机会）。比 chance 更正式，常指有利的客观时机。复数 opportunities。",
 ["机会", "时机"],
 "opportunity to do（做…的机会）, job opportunity（就业机会）, equal opportunity（平等机会）",
 "The internship provided a valuable opportunity to gain work experience.", "这次实习提供了获得工作经验的宝贵机会。",
 "ob-（向）+ port（港）→ 靠近港口的时机 → 机会",
 ["chance"], [], "机会", "就业"),
("process", "/ˈprəʊses/ · /ˈprɑːses/", "n. / v.",
 "n. ①过程，进程（in the process of）；②工序。v. ①加工；②处理（process data / an application）。process of doing。processor（处理器）。",
 ["过程", "处理", "加工"],
 "in the process of（在…过程中）, process data（处理数据）, learning process（学习过程）",
 "Writing is often described as a process rather than a single event.", "写作常常被描述为一个过程，而不是一次性的行为。",
 "pro-（向前）+ cess（走）→ 向前走 → 过程",
 ["procedure"], [], "过程", "学术"),
("challenge", "/ˈtʃælɪndʒ/", "n. / v.",
 "n. ①挑战，艰巨任务（face / pose a challenge）；②质疑。v. ①向…挑战；②质疑（challenge an idea）。challenging（有挑战性的）。",
 ["挑战", "质疑"],
 "face a challenge（面临挑战）, pose a challenge（构成挑战）, challenge an idea（质疑某一观点）",
 "Climate change poses a serious challenge to coastal cities.", "气候变化对沿海城市构成严峻挑战。",
 "原指‘传唤到法庭’，引申为叫阵 → 挑战",
 ["difficulty"], [], "挑战", "环境"),
("decline", "/dɪˈklaɪn/", "n. / v.",
 "n. 下降，衰退（a decline in）。v. ①下降，减少；②衰退；③婉拒（decline an invitation）。in decline（在衰退中）。反义 increase / rise。",
 ["下降", "衰退", "婉拒"],
 "a decline in（在…方面的下降）, in decline（在衰退中）, decline an invitation（婉拒邀请）",
 "There has been a sharp decline in the number of rural primary schools.", "农村小学的数量已急剧下降。",
 "de-（向下）+ cline（倾斜）→ 向下倾斜 → 下降",
 ["decrease", "drop"], ["increase", "rise"], "下降", "社会"),
("affect", "/əˈfekt/", "v.",
 "v. ①影响（affect sb/sth，不接 on）；②感动；（疾病）侵袭。易混：effect 多为名词‘结果/影响’；affect 是动词。be affected by。派生 affection（感情）。",
 ["影响", "感动"],
 "be affected by（受…影响）, affect performance（影响表现）, seriously affect（严重影响）",
 "Air pollution can seriously affect children's lung development.", "空气污染会严重影响儿童的肺部发育。",
 "af-（向）+ fect（做）→ 对…起作用 → 影响",
 ["influence", "impact"], [], "影响", "环境"),
("economic", "/ˌiːkəˈnɒmɪk/ · /ˌekəˈnɑːmɪk/", "adj.",
 "adj. ①经济的，经济学的（economic growth / policy）；②有利可图的。易混 economical（节约的，省钱的）。economics（经济学）；economy（经济）。",
 ["经济的", "经济学的"],
 "economic growth（经济增长）, economic policy（经济政策）, economic development（经济发展）",
 "Economic growth does not always lead to a better environment.", "经济增长并不总是带来更好的环境。",
 "eco-（家计）+ -nomic → 家国理财 → 经济的",
 ["financial"], [], "经济的", "经济"),
("global", "/ˈɡləʊbl/ · /ˈɡloʊbl/", "adj.",
 "adj. ①全球的，全世界的（global warming / economy）；②整体的。globally。名词 globe（地球）。反义 local。",
 ["全球的", "全世界的", "整体的"],
 "global warming（全球变暖）, global economy（全球经济）, globalisation（全球化，英式 -sation）",
 "Global warming has become a central issue in international policy.", "全球变暖已成为国际政策中的核心问题。",
 "globe（球体）+ -al → 整个地球的",
 ["worldwide"], ["local"], "全球的", "环境"),
("environment", "/ɪnˈvaɪrənmənt/", "n.",
 "n. ①环境，生态环境（protect the environment）；②周围状况，工作/学习环境。environmental（环境的）；environmentally friendly（环保的）。",
 ["环境", "周围状况"],
 "protect the environment（保护环境）, working environment（工作环境）, environmental policy（环境政策）",
 "Protecting the environment requires both policy and public support.", "保护环境既需要政策，也需要公众支持。",
 "en-（使在其中）+ viron（围绕）→ 围绕之物 → 环境",
 ["surroundings"], [], "环境", "环境"),
("patient", "/ˈpeɪʃnt/", "n. / adj.",
 "n. 病人（hospital patients）。adj. 有耐心的（be patient with）。patience（耐心）；impatient（不耐烦的）。名词与形容词拼写相同、重音相同，靠语境区分。",
 ["病人", "有耐心的"],
 "hospital patients（医院病人）, be patient with（对…有耐心）, patient care（病人护理）",
 "Doctors should be patient with elderly patients during consultation.", "医生在问诊时应对老年病人有耐心。",
 "pati（忍受）→ 能忍受等待 → 耐心；接受治疗者 → 病人",
 ["sick person"], ["impatient"], "病人", "健康"),
("security", "/sɪˈkjʊərəti/ · /səˈkjʊrəti/", "n.",
 "n. ①安全，保障（national / job security）；②保安措施；③证券（securities，复数）。security camera（监控摄像头）。形容词 secure；反义 insecurity。",
 ["安全", "保障", "保安"],
 "national security（国家安全）, job security（职业保障）, security measures（安全措施）",
 "Job security has declined in several service industries.", "若干服务行业的职业保障已经下降。",
 "se-（离开）+ cure（关心）→ 无需担心 → 安全",
 ["safety"], ["insecurity"], "安全", "社会"),
("access", "/ˈækses/", "n. / v.",
 "n. ①通道，入口；②使用权，机会（have access to）。v. 访问，获取（access information）。accessible（可获得的；无障碍的）。易混 assess（评估）。",
 ["进入", "使用权", "获取"],
 "have access to（有权使用/进入）, access to education（受教育机会）, access information（获取信息）",
 "Not all students have equal access to high-quality online resources.", "并非所有学生都能平等获得高质量的在线资源。",
 "ac-（向）+ cess（走）→ 走得进去 → 进入/使用权",
 ["entry"], [], "使用权", "教育"),
("survey", "/ˈsɜːveɪ/ · /ˈsɜːrveɪ/", "n. / v.",
 "n. ①调查（conduct / carry out a survey；名词重音多在前）；②测量。v. ①调查；②审视（动词亦可读 /səˈveɪ/）。survey of / on。questionnaire 是问卷工具，survey 是调查活动。",
 ["调查", "测量", "审视"],
 "conduct a survey（进行调查）, a survey of（对…的调查）, survey results（调查结果）",
 "A recent survey of graduates found that internships improved job prospects.", "一项针对毕业生的近期调查发现，实习能改善就业前景。",
 "sur-（在上）+ vey（看）→ 从上往下看 → 调查/审视",
 ["poll", "study"], [], "调查", "学术"),
("writing", "/ˈraɪtɪŋ/", "n.",
 "n. ①写作，书写（academic writing）；②作品，文字（sb's writings）；③字迹。writing skills。动词 write（不规则：wrote, written）。",
 ["写作", "作品", "字迹"],
 "academic writing（学术写作）, writing skills（写作能力）, in writing（以书面形式）",
 "Academic writing requires clear organisation and accurate vocabulary.", "学术写作需要清晰的结构和准确的词汇。",
 "write + -ing → 写的行为或产物",
 ["composition"], [], "写作", "校园"),
("employee", "/ɪmˈplɔɪiː/ · /ˌemplɔɪˈiː/", "n.",
 "n. 雇员，员工。employer（雇主）；employment（就业）；unemployment（失业）；employ（雇用）。-ee 表动作承受者，-er 表发出者。",
 ["雇员", "员工"],
 "company employees（公司员工）, employee benefits（员工福利）, former employee（前雇员）",
 "The company provides training programmes for new employees.", "该公司为新员工提供培训项目。",
 "employ（雇用）+ -ee（受事）→ 被雇用者",
 ["worker", "staff"], ["employer"], "雇员", "就业"),
("major", "/ˈmeɪdʒə(r)/ · /ˈmeɪdʒər/", "adj. / n. / v.",
 "adj. ①主要的，重大的（a major problem）；②大调的。n. ①专业（a history major）；②主修学生。v. 主修（major in）。反义 minor。majority（大多数）。",
 ["主要的", "专业", "主修"],
 "a major problem（一个重大问题）, major in（主修）, the majority of（大多数…）",
 "A major challenge for universities is to improve teaching quality.", "大学面临的一个重大挑战是提高教学质量。",
 "maj-（大）+ -or → 较大的 → 主要的",
 ["main", "chief"], ["minor"], "主要的", "校园"),
("subject", "/ˈsʌbdʒɪkt/", "n. / adj. / v.",
 "n. ①科目，学科；②主题；③主语；④实验对象（名词重音在前）。adj. 易受…的（be subject to）。v. 使服从（subject sb to，动词常读 /səbˈdʒekt/）。",
 ["科目", "主题", "使服从"],
 "school subjects（学校科目）, be subject to（易受…；须服从）, the subject of（…的主题）",
 "History remains a popular subject among first-year students.", "历史仍是一年级学生中颇受欢迎的科目。",
 "sub-（在下）+ ject（投）→ 被置于某主题之下",
 ["topic", "discipline"], [], "科目", "校园"),
("community", "/kəˈmjuːnəti/", "n.",
 "n. ①社区；②团体，界（the academic community）；③共同体。community service（社区服务）。sense of community（社区归属感）。",
 ["社区", "团体", "共同体"],
 "local community（当地社区）, academic community（学术界）, community service（社区服务）",
 "Universities are encouraged to work more closely with the local community.", "大学被鼓励与当地社区开展更密切的合作。",
 "com-（共同）+ mun（服务）→ 共同生活的群体",
 ["society", "neighbourhood"], [], "社区", "社会"),
("economy", "/ɪˈkɒnəmi/ · /ɪˈkɑːnəmi/", "n.",
 "n. ①经济（the global / market economy）；②节约（economy of words 措辞简练）。economic（经济的）；economical（节约的）。复数 economies。",
 ["经济", "节约"],
 "global economy（全球经济）, market economy（市场经济）, the local economy（地方经济）",
 "Tourism plays an important role in the local economy.", "旅游业在地方经济中发挥着重要作用。",
 "eco-（家）+ nomy（管理）→ 家政管理 → 经济",
 ["the market"], [], "经济", "经济"),
("derive", "/dɪˈraɪv/", "v.",
 "v. ①源自，由…派生（derive from）；②获得（derive pleasure / benefit from）。derivation（派生）；derivative（派生物；衍生产品）。词源学常用。",
 ["源自", "获得", "派生"],
 "derive from（源自）, derive benefit from（从…中获得益处）, be derived from（由…派生）",
 "Many English academic words are derived from Latin and Greek.", "许多英语学术词汇源自拉丁语和希腊语。",
 "de-（从）+ riv（河流）→ 从河里引出 → 源自",
 ["originate", "obtain"], [], "源自", "学术"),
("select", "/sɪˈlekt/", "v.",
 "v. 选择，挑选（select sb/sth for）。比 choose 更正式，强调从范围内审慎挑选。selection（选择；选集）；selective（有选择的）。selected（精选的）。",
 ["选择", "挑选"],
 "select for（为…挑选）, randomly selected（随机抽取的）, selection process（选拔过程）",
 "Participants were randomly selected from three universities.", "参与者是从三所大学中随机抽取的。",
 "se-（分开）+ lect（挑选）→ 分出来选 → 挑选",
 ["choose", "pick"], [], "挑选", "学术"),
("condition", "/kənˈdɪʃn/", "n.",
 "n. ①状况，状态（working / living conditions，常用复数）；②条件（on condition that 条件是）；③疾病（a heart condition）。v. 使习惯于（较少考）。conditional（有条件的）。",
 ["状况", "条件", "疾病"],
 "working conditions（工作条件）, on condition that（条件是）, weather conditions（天气状况）",
 "Poor working conditions may affect employees' health and productivity.", "恶劣的工作条件可能影响员工的健康与效率。",
 "con-（共同）+ dit（给予）→ 给定的情形 → 条件/状况",
 ["state", "requirement"], [], "状况", "社会"),
("data", "/ˈdeɪtə/ · /ˈdætə/", "n.",
 "n. 数据，资料。原为 datum 的复数，现代英语常作不可数：the data is / are 皆可见，学术写作仍有人用 are。collect / analyse data。database（数据库）。",
 ["数据", "资料"],
 "collect data（收集数据）, analyse data（分析数据）, data analysis（数据分析）",
 "The researchers collected data from more than five hundred participants.", "研究者从五百多名参与者那里收集了数据。",
 "datum（给定的事实）的复数 → 数据",
 ["information"], [], "数据", "学术"),
("impact", "/ˈɪmpækt/", "n. / v.",
 "n. ①影响，作用（have / have an impact on）；②冲击。v. 影响（impact on / impact sth，口语渐多，正式文体仍多用 have an impact on）。",
 ["影响", "冲击", "作用"],
 "have an impact on（对…有影响）, a major impact（重大影响）, environmental impact（环境影响）",
 "Online learning has had a major impact on higher education.", "在线学习已对高等教育产生重大影响。",
 "im-（向内）+ pact（压）→ 压进去 → 冲击/影响",
 ["effect", "influence"], [], "影响", "教育"),
("avoid", "/əˈvɔɪd/", "v.",
 "v. ①避免，避开（avoid doing，后接动名词，不接 to do）；②躲避。avoidable（可避免的）；avoidance（回避）。avoid sb/sth。",
 ["避免", "避开", "躲避"],
 "avoid doing（避免做…）, avoid the risk of（避免…风险）, avoid eye contact（避免目光接触）",
 "Writers should avoid using informal language in academic essays.", "写作者应避免在学术短文中使用非正式语言。",
 "a-（离开）+ void（空）→ 躲开使成空 → 避免",
 ["prevent", "keep away from"], [], "避免", "学术"),
("consumer", "/kənˈsjuːmə(r)/ · /kənˈsuːmər/", "n.",
 "n. 消费者。consumer goods（消费品）；consumer behaviour（消费行为，英式 -our）。consume（消费）；consumption（消费量）；producer 相对。",
 ["消费者", "顾客"],
 "consumer goods（消费品）, consumer behaviour（消费行为）, consumer rights（消费者权益）",
 "Consumer behaviour has changed with the growth of online shopping.", "随着网上购物的增长，消费行为已经发生变化。",
 "consume（消耗）+ -er → 消耗者 → 消费者",
 ["customer", "buyer"], ["producer"], "消费者", "经济"),
("physical", "/ˈfɪzɪkl/", "adj.",
 "adj. ①身体的（physical health / activity）；②物质的，有形的（physical environment）；③物理的。physically。physics（物理学）；physician（内科医生）。",
 ["身体的", "物质的", "物理的"],
 "physical activity（体育活动）, physical health（身体健康）, physical environment（物质环境）",
 "Physical activity is linked to better concentration in class.", "体育活动与课堂上更好的注意力有关。",
 "physic（自然/身体）+ -al → 身体的/物质的",
 ["bodily"], ["mental"], "身体的", "健康"),
("risk", "/rɪsk/", "n. / v.",
 "n. 风险，危险（at risk；the risk of）。v. 冒…的危险（risk doing / sth）。take a risk；reduce / increase the risk。risky（有风险的）。",
 ["风险", "危险", "冒…的危险"],
 "at risk（处于危险中）, the risk of（…的风险）, take a risk（冒险）",
 "Lack of exercise increases the risk of heart disease.", "缺乏锻炼会增加患心脏病的风险。",
 "原义‘危崖’，引申为可能的损失",
 ["danger", "hazard"], ["safety"], "风险", "健康"),
("academic", "/ˌækəˈdemɪk/", "adj. / n.",
 "adj. ①学术的（academic performance / writing）；②学院的；③不切实际的。n. 大学教师，学者。academy（学院）；academically。",
 ["学术的", "学者"],
 "academic performance（学业表现）, academic writing（学术写作）, academic year（学年）",
 "Academic performance is influenced by both teaching quality and study habits.", "学业表现既受教学质量影响，也受学习习惯影响。",
 "源自 Plato 的 Academy（学园）",
 ["scholarly"], [], "学术的", "校园"),
("instead", "/ɪnˈsted/", "adv.",
 "adv. ①代替，反而（单独用，表‘作为替代’）；②instead of + 名词/动名词（而不是）。不可说 instead to do。语气：用 B 替换 A。",
 ["代替", "反而", "而不是"],
 "instead of（而不是）, do sth instead（改为做某事）, instead of doing（不做…而做）",
 "Many students sent emails instead of attending the office hour.", "许多学生发了邮件，而没有去参加办公答疑时间。",
 "in + stead（位置）→ 处在其位置上 → 代替",
 ["rather"], [], "而不是", "通用"),
("allow", "/əˈlaʊ/", "v.",
 "v. ①允许（allow sb to do；allow doing）；②给予，留出（allow time for）。allow for（考虑到，留有余地）。反义 forbid / prevent。",
 ["允许", "准许", "留出"],
 "allow sb to do（允许某人做）, allow for（考虑到）, allow time for（为…留出时间）",
 "The rules allow students to use dictionaries in the writing test.", "规则允许学生在写作考试中使用词典。",
 "与 ‘praise/admit’ 旧义相关，后固定为‘许可’",
 ["permit", "let"], ["forbid"], "允许", "校园"),
("force", "/fɔːs/ · /fɔːrs/", "n. / v.",
 "n. ①力，力量；②武力；③影响力（a driving force）；④一群人（the labour force 劳动力）。v. 强迫（force sb to do）。by force（用武力）。forced（被迫的）。",
 ["力量", "强迫", "武力"],
 "labour force（劳动力）, force sb to do（强迫某人做）, a driving force（推动力）",
 "Economic pressure may force graduates to accept jobs they do not prefer.", "经济压力可能迫使毕业生接受并不心仪的工作。",
 "原义‘强壮’，引申为迫使别人行动的力",
 ["power", "compel"], [], "力量", "经济"),
("graduate", "/ˈɡrædʒuət/", "n. / v.",
 "n. 毕业生（a university graduate；名词读 /ˈɡrædʒuət/）。v. 毕业（graduate from；动词常读 /ˈɡrædʒueɪt/）。graduation（毕业典礼/毕业）；undergraduate（本科生）；postgraduate（研究生）。",
 ["毕业生", "毕业"],
 "university graduate（大学毕业生）, graduate from（毕业于）, graduate school（研究生院）",
 "A growing number of graduates choose to start their own businesses.", "越来越多的毕业生选择自主创业。",
 "grad（步、级）+ -ate → 完成一级学业 → 毕业",
 [], ["undergraduate"], "毕业生", "就业"),
("remain", "/rɪˈmeɪn/", "v.",
 "v. ①仍然是，保持（remain calm / unchanged）；②剩下，遗留（little remains）；③留下。n. remains（残骸，遗迹，遗体，常用复数）。remainder（剩余部分）。",
 ["仍然是", "保持", "剩下"],
 "remain unchanged（保持不变）, remain seated（继续坐着）, the remains（遗迹；遗体）",
 "The unemployment rate remained high throughout the decade.", "失业率在那十年间一直居高不下。",
 "re-（再）+ main（留）→ 留下来",
 ["stay", "continue"], ["leave"], "仍然是", "经济"),
("tax", "/tæks/", "n. / v.",
 "n. 税，税款（income / sales tax）。v. ①对…征税；②使负重担（tax sb's patience）。taxpayer（纳税人）；taxation（征税）。tax-free（免税的）。",
 ["税", "征税"],
 "income tax（所得税）, tax policy（税收政策）, tax-free（免税的）",
 "The government reduced income tax to encourage spending.", "政府降低所得税以鼓励消费。",
 "原义‘评估负担’，后专指税收",
 ["duty"], [], "税", "经济"),
("attach", "/əˈtætʃ/", "v.",
 "v. ①附上，贴上（attach sth to）；②使附属；③认为有（attach importance to 重视，四级高频）。attached to（附属于；依恋）。attachment（附件；依恋）。",
 ["附上", "重视", "附属"],
 "attach importance to（重视）, attach sth to（把…附在…上）, an email attachment（电子邮件附件）",
 "Educators attach great importance to critical reading skills.", "教育者非常重视批判性阅读能力。",
 "at-（向）+ tach（钉住）→ 钉上去 → 附上",
 ["fasten", "join"], ["detach"], "重视", "学术"),
("growth", "/ɡrəʊθ/ · /ɡroʊθ/", "n.",
 "n. ①增长，生长（economic growth；不可数常见）；②增长量；③生长物。grow（生长，不规则：grew, grown）。growth rate（增长率）。反义 decline。",
 ["增长", "生长", "发展"],
 "economic growth（经济增长）, growth rate（增长率）, personal growth（个人成长）",
 "Rapid economic growth has created both opportunities and environmental costs.", "快速的经济增长既带来了机会，也带来了环境代价。",
 "grow + -th（名词）→ 生长/增长",
 ["increase", "expansion"], ["decline"], "增长", "经济"),
("issue", "/ˈɪʃuː/ · /ˈɪsjuː/", "n. / v.",
 "n. ①问题，议题（a social issue；the issue of）；②一期（the latest issue of a journal）；③发行。v. ①发行，公布；②发给。at issue（争论中的）。",
 ["问题", "议题", "发行"],
 "social issue（社会问题）, the issue of（…的问题）, issue a report（发布报告）",
 "Housing remains a major issue for young people in large cities.", "住房仍是大城市年轻人面临的一个主要问题。",
 "原义‘流出’，引申为发布出去的事物/问题",
 ["problem", "topic"], [], "问题", "社会"),
("lower", "/ˈləʊə(r)/ · /ˈloʊər/", "adj. / v.",
 "adj. 较低的（lower cost / rate；low 的比较级）。v. ①降低，放下（lower prices / one's voice）；②减弱。lower than。反义 raise / higher。",
 ["较低的", "降低", "放下"],
 "lower the cost（降低成本）, lower than（低于）, lower one's voice（压低声音）",
 "The new policy aims to lower the cost of higher education.", "新政策旨在降低高等教育的成本。",
 "low（低）+ -er → 更低；作动词即‘使变低’",
 ["reduce"], ["raise"], "降低", "经济"),
("resident", "/ˈrezɪdənt/", "n. / adj.",
 "n. 居民，住户（local residents）。adj. 居住的，常驻的（resident students 住校生）。reside（居住）；residence（住所）；residential（住宅的）。",
 ["居民", "住户", "居住的"],
 "local residents（当地居民）, resident students（住校生）, residential area（住宅区）",
 "Local residents expressed concern about the planned factory.", "当地居民对计划中的工厂表示担忧。",
 "re-（再）+ sid（坐）→ 坐定于某处 → 居住",
 ["inhabitant"], ["visitor"], "居民", "社会"),
]

assert len(ROWS) == 80
WORDS = numbered(ROWS)
assert [w["word"] for w in WORDS] == [r[0] for r in ROWS]


def cet4_words():
    out = []
    for w in WORDS:
        w = dict(w)
        tag = dict(w.get("examTag") or {})
        tag["source"] = "大学英语四级"
        w["examTag"] = tag
        w["mnemonic"] = w.get("root") or ""
        w["exampleEN"] = w.get("exampleEn") or ""
        w["exampleCN"] = w.get("exampleZh") or ""
        out.append(w)
    return out


if __name__ == "__main__":
    import json
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from build_cet4_lists import render_html

    root = Path(__file__).resolve().parents[1]
    excel = [
        "according to", "author", "accord", "likely", "system", "kid", "interest",
        "identify", "happen", "technology", "improve", "benefit", "social", "provide",
        "require", "item", "include", "market", "blank", "adult", "product", "activity",
        "local", "comprehension", "result", "create", "support", "focus", "concern",
        "essay", "career", "project", "design", "finding", "ability", "disease",
        "digital", "tend", "decade", "average", "culture", "opportunity", "process",
        "challenge", "decline", "affect", "economic", "global", "environment",
        "patient", "security", "access", "survey", "writing", "employee", "major",
        "subject", "community", "economy", "derive", "select", "condition", "data",
        "impact", "avoid", "consumer", "physical", "risk", "academic", "instead",
        "allow", "force", "graduate", "remain", "tax", "attach", "growth", "issue",
        "lower", "resident",
    ]
    ws = cet4_words()
    got = [w["word"] for w in ws]
    if got != excel:
        raise SystemExit("order mismatch: %s" % [(a, b) for a, b in zip(got, excel) if a != b][:5] or "len %s/%s" % (len(got), len(excel)))
    for w in ws:
        if len(w["acceptCN"]) < 2:
            raise SystemExit("acceptCN < 2: %s" % w["word"])
        if len(w["meaning"]) < 24:
            raise SystemExit("thin meaning: %s" % w["word"])
        if not w.get("exampleEn") or not w.get("exampleZh"):
            raise SystemExit("missing example: %s" % w["word"])
        if not w.get("ipa") or "/" not in w["ipa"]:
            raise SystemExit("ipa: %s" % w["word"])

    meta = {
        "listNo": 1,
        "band": "high",
        "title": "单元 1",
        "published": True,
        "sourceNote": "Headword order from 四级单词List1-35.xlsx; cards rewritten to gaozhong field standard.",
        "words": ws,
    }
    jp = root / "library" / "study" / "vocab-cet4-data" / "list-01.json"
    jp.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    html = render_html(meta)
    html = html.replace("const wordData = [", "var wordData = [", 1)
    snip = (
        '</style>\n<!-- yysd:hide-legacy-test --><style id="yysd-hide-legacy-test">'
        '.nav-tab[data-mode="test"],#testSection,.test-section,[data-mode="test"]{display:none!important}'
        "</style>\n</head>"
    )
    if "yysd-hide-legacy-test" not in html:
        html = html.replace("</style>\n</head>", snip, 1)
    out = root / "library" / "study" / "vocab-cet4" / "四级单词LIST1.html"
    out.write_text(html, encoding="utf-8")
    print("LIST1", len(ws), "words →", out.name)
